package fr.prima.jna.opencv.cxcore;
/**
 * <i>native declaration : cxcore.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvGraphScanner extends com.ochafik.lang.jnaerator.runtime.Structure<CvGraphScanner, CvGraphScanner.ByValue, CvGraphScanner.ByReference> {
	/**
	 * current graph vertex (or current edge origin)<br>
	 * C type : CvGraphVtx*
	 */
	public fr.prima.jna.opencv.cxtypes.CvGraphVtx.ByReference vtx;
	/**
	 * current graph edge destination vertex<br>
	 * C type : CvGraphVtx*
	 */
	public fr.prima.jna.opencv.cxtypes.CvGraphVtx.ByReference dst;
	/**
	 * current edge<br>
	 * C type : CvGraphEdge*
	 */
	public fr.prima.jna.opencv.cxtypes.CvGraphEdge.ByReference edge;
	/**
	 * the graph<br>
	 * C type : CvGraph*
	 */
	public fr.prima.jna.opencv.cxtypes.CvGraph.ByReference graph;
	/**
	 * the graph vertex stack<br>
	 * C type : CvSeq*
	 */
	public fr.prima.jna.opencv.cxtypes.CvSeq.ByReference stack;
	/// the lower bound of certainly visited vertices
	public int index;
	/// event mask
	public int mask;
	public CvGraphScanner() {
		super();
	}
	/**
	 * @param vtx current graph vertex (or current edge origin)<br>
	 * C type : CvGraphVtx*<br>
	 * @param dst current graph edge destination vertex<br>
	 * C type : CvGraphVtx*<br>
	 * @param edge current edge<br>
	 * C type : CvGraphEdge*<br>
	 * @param graph the graph<br>
	 * C type : CvGraph*<br>
	 * @param stack the graph vertex stack<br>
	 * C type : CvSeq*<br>
	 * @param index the lower bound of certainly visited vertices<br>
	 * @param mask event mask
	 */
	public CvGraphScanner(fr.prima.jna.opencv.cxtypes.CvGraphVtx.ByReference vtx, fr.prima.jna.opencv.cxtypes.CvGraphVtx.ByReference dst, fr.prima.jna.opencv.cxtypes.CvGraphEdge.ByReference edge, fr.prima.jna.opencv.cxtypes.CvGraph.ByReference graph, fr.prima.jna.opencv.cxtypes.CvSeq.ByReference stack, int index, int mask) {
		super();
		this.vtx = vtx;
		this.dst = dst;
		this.edge = edge;
		this.graph = graph;
		this.stack = stack;
		this.index = index;
		this.mask = mask;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvGraphScanner newInstance() { return new CvGraphScanner(); }
	public static CvGraphScanner[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvGraphScanner.class, arrayLength);
	}
	public static class ByReference extends CvGraphScanner implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvGraphScanner implements com.sun.jna.Structure.ByValue {}
}
