package fr.prima.jna.opencv.cxcore;
/**
 * <i>native declaration : cxcore.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvNArrayIterator extends com.ochafik.lang.jnaerator.runtime.Structure<CvNArrayIterator, CvNArrayIterator.ByValue, CvNArrayIterator.ByReference> {
	/// number of arrays
	public int count;
	/// number of dimensions to iterate
	public int dims;
	/**
	 * maximal common linear size: { width = size, height = 1 }<br>
	 * C type : CvSize
	 */
	public fr.prima.jna.opencv.cxtypes.CvSize size;
	/**
	 * pointers to the array slices<br>
	 * C type : uchar*[10]
	 */
	public com.sun.jna.Pointer[] ptr = new com.sun.jna.Pointer[(10)];
	/**
	 * for internal use<br>
	 * C type : int[CV_MAX_DIM]
	 */
	public int[] stack = new int[(fr.prima.jna.opencv.cxtypes.CxtypesLibrary.CV_MAX_DIM)];
	/**
	 * pointers to the headers of the<br>
	 * matrices that are processed<br>
	 * C type : CvMatND*[10]
	 */
	public fr.prima.jna.opencv.cxtypes.CvMatND.ByReference[] hdr = new fr.prima.jna.opencv.cxtypes.CvMatND.ByReference[(10)];
	public CvNArrayIterator() {
		super();
	}
	/**
	 * @param count number of arrays<br>
	 * @param dims number of dimensions to iterate<br>
	 * @param size maximal common linear size: { width = size, height = 1 }<br>
	 * C type : CvSize<br>
	 * @param ptr pointers to the array slices<br>
	 * C type : uchar*[10]<br>
	 * @param stack for internal use<br>
	 * C type : int[CV_MAX_DIM]<br>
	 * @param hdr pointers to the headers of the<br>
	 * matrices that are processed<br>
	 * C type : CvMatND*[10]
	 */
	public CvNArrayIterator(int count, int dims, fr.prima.jna.opencv.cxtypes.CvSize size, com.sun.jna.Pointer ptr[], int stack[], fr.prima.jna.opencv.cxtypes.CvMatND.ByReference hdr[]) {
		super();
		this.count = count;
		this.dims = dims;
		this.size = size;
		if (ptr.length != this.ptr.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.ptr = ptr;
		if (stack.length != this.stack.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.stack = stack;
		if (hdr.length != this.hdr.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.hdr = hdr;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvNArrayIterator newInstance() { return new CvNArrayIterator(); }
	public static CvNArrayIterator[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvNArrayIterator.class, arrayLength);
	}
	public static class ByReference extends CvNArrayIterator implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvNArrayIterator implements com.sun.jna.Structure.ByValue {}
}
