package fr.prima.jna.opencv.cxcore;
/**
 * <i>native declaration : cxcore.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvTreeNodeIterator extends com.ochafik.lang.jnaerator.runtime.Structure<CvTreeNodeIterator, CvTreeNodeIterator.ByValue, CvTreeNodeIterator.ByReference> {
	/// C type : const void*
	public com.sun.jna.Pointer node;
	public int level;
	public int max_level;
	public CvTreeNodeIterator() {
		super();
	}
	/// @param node C type : const void*
	public CvTreeNodeIterator(com.sun.jna.Pointer node, int level, int max_level) {
		super();
		this.node = node;
		this.level = level;
		this.max_level = max_level;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvTreeNodeIterator newInstance() { return new CvTreeNodeIterator(); }
	public static CvTreeNodeIterator[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvTreeNodeIterator.class, arrayLength);
	}
	public static class ByReference extends CvTreeNodeIterator implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvTreeNodeIterator implements com.sun.jna.Structure.ByValue {}
}
