package fr.prima.jna.opencv.cvtypes;
/**
 * <i>native declaration : cvtypes.h:97</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvChainPtReader extends com.ochafik.lang.jnaerator.runtime.Structure<CvChainPtReader, CvChainPtReader.ByValue, CvChainPtReader.ByReference> {
	public CvChainPtReader() {
		super();
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvChainPtReader newInstance() { return new CvChainPtReader(); }
	public static CvChainPtReader[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvChainPtReader.class, arrayLength);
	}
	public static class ByReference extends CvChainPtReader implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvChainPtReader implements com.sun.jna.Structure.ByValue {}
}
