package fr.prima.jna.opencv.cvtypes;
/**
 * <i>native declaration : cvtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvConnectedComp extends com.ochafik.lang.jnaerator.runtime.Structure<CvConnectedComp, CvConnectedComp.ByValue, CvConnectedComp.ByReference> {
	/// area of the connected component
	public double area;
	/**
	 * average color of the connected component<br>
	 * C type : CvScalar
	 */
	public fr.prima.jna.opencv.cxtypes.CvScalar value;
	/**
	 * ROI of the component<br>
	 * C type : CvRect
	 */
	public fr.prima.jna.opencv.cxtypes.CvRect rect;
	/**
	 * optional component boundary<br>
	 * (the contour might have child contours corresponding to the holes)<br>
	 * C type : CvSeq*
	 */
	public fr.prima.jna.opencv.cxtypes.CvSeq.ByReference contour;
	public CvConnectedComp() {
		super();
	}
	/**
	 * @param area area of the connected component<br>
	 * @param value average color of the connected component<br>
	 * C type : CvScalar<br>
	 * @param rect ROI of the component<br>
	 * C type : CvRect<br>
	 * @param contour optional component boundary<br>
	 * (the contour might have child contours corresponding to the holes)<br>
	 * C type : CvSeq*
	 */
	public CvConnectedComp(double area, fr.prima.jna.opencv.cxtypes.CvScalar value, fr.prima.jna.opencv.cxtypes.CvRect rect, fr.prima.jna.opencv.cxtypes.CvSeq.ByReference contour) {
		super();
		this.area = area;
		this.value = value;
		this.rect = rect;
		this.contour = contour;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvConnectedComp newInstance() { return new CvConnectedComp(); }
	public static CvConnectedComp[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvConnectedComp.class, arrayLength);
	}
	public static class ByReference extends CvConnectedComp implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvConnectedComp implements com.sun.jna.Structure.ByValue {}
}
