package fr.prima.jna.opencv.cvtypes;
/**
 * <i>native declaration : cvtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvHuMoments extends com.ochafik.lang.jnaerator.runtime.Structure<CvHuMoments, CvHuMoments.ByValue, CvHuMoments.ByReference> {
	/// Hu invariants
	public double hu1;
	/// Hu invariants
	public double hu2;
	/// Hu invariants
	public double hu3;
	/// Hu invariants
	public double hu4;
	/// Hu invariants
	public double hu5;
	/// Hu invariants
	public double hu6;
	/// Hu invariants
	public double hu7;
	public CvHuMoments() {
		super();
	}
	/**
	 * @param hu1 Hu invariants<br>
	 * @param hu2 Hu invariants<br>
	 * @param hu3 Hu invariants<br>
	 * @param hu4 Hu invariants<br>
	 * @param hu5 Hu invariants<br>
	 * @param hu6 Hu invariants<br>
	 * @param hu7 Hu invariants
	 */
	public CvHuMoments(double hu1, double hu2, double hu3, double hu4, double hu5, double hu6, double hu7) {
		super();
		this.hu1 = hu1;
		this.hu2 = hu2;
		this.hu3 = hu3;
		this.hu4 = hu4;
		this.hu5 = hu5;
		this.hu6 = hu6;
		this.hu7 = hu7;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvHuMoments newInstance() { return new CvHuMoments(); }
	public static CvHuMoments[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvHuMoments.class, arrayLength);
	}
	public static class ByReference extends CvHuMoments implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvHuMoments implements com.sun.jna.Structure.ByValue {}
}
