package fr.prima.jna.opencv.cvtypes;
/**
 * JNA Wrapper for library <b>cvtypes</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface CvtypesLibrary extends com.sun.jna.Library {
	public static final java.lang.String JNA_LIBRARY_NAME = com.ochafik.lang.jnaerator.runtime.LibraryExtractor.getLibraryPath("cvtypes", true, fr.prima.jna.opencv.cvtypes.CvtypesLibrary.class);
	public static final com.sun.jna.NativeLibrary JNA_NATIVE_LIB = com.sun.jna.NativeLibrary.getInstance(fr.prima.jna.opencv.cvtypes.CvtypesLibrary.JNA_LIBRARY_NAME, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	public static final fr.prima.jna.opencv.cvtypes.CvtypesLibrary INSTANCE = (fr.prima.jna.opencv.cvtypes.CvtypesLibrary)com.sun.jna.Native.loadLibrary(fr.prima.jna.opencv.cvtypes.CvtypesLibrary.JNA_LIBRARY_NAME, fr.prima.jna.opencv.cvtypes.CvtypesLibrary.class, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_RETR_EXTERNAL = 0;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_RETR_LIST = 1;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_RETR_CCOMP = 2;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_RETR_TREE = 3;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_CHAIN_CODE = 0;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_CHAIN_APPROX_NONE = 1;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_CHAIN_APPROX_SIMPLE = 2;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_CHAIN_APPROX_TC89_L1 = 3;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_CHAIN_APPROX_TC89_KCOS = 4;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_LINK_RUNS = 5;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_SUBDIV2D_VIRTUAL_POINT_FLAG = (1 << 30);
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_DIST_USER = -1;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_DIST_L1 = 1;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_DIST_L2 = 2;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_DIST_C = 3;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_DIST_L12 = 4;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_DIST_FAIR = 5;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_DIST_WELSCH = 6;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_DIST_HUBER = 7;
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_HAAR_MAGIC_VAL = 1112539136;
	/// <i>native declaration : cvtypes.h</i>
	public static final java.lang.String CV_TYPE_NAME_HAAR = "opencv-haar-classifier";
	/// <i>native declaration : cvtypes.h</i>
	public static final int CV_HAAR_FEATURE_MAX = 3;
}
