package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Cv64suf extends com.ochafik.lang.jnaerator.runtime.Union<Cv64suf, Cv64suf.ByValue, Cv64suf.ByReference> {
	/// C type : int64
	public long i;
	/// C type : uint64
	public long u;
	public double f;
	public Cv64suf() {
		super();
	}
	public Cv64suf(double f) {
		super();
		this.f = f;
		setType(java.lang.Double.TYPE);
	}
	/// @param i_or_u C type : int64, or C type : uint64
	public Cv64suf(long i_or_u) {
		super();
		this.u = this.i = i_or_u;
		setType(java.lang.Long.TYPE);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected Cv64suf newInstance() { return new Cv64suf(); }
	public static Cv64suf[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Union.newArray(Cv64suf.class, arrayLength);
	}
	public static class ByReference extends Cv64suf implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends Cv64suf implements com.sun.jna.Structure.ByValue {}
}
