package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvAttrList extends com.ochafik.lang.jnaerator.runtime.Structure<CvAttrList, CvAttrList.ByValue, CvAttrList.ByReference> {
	/**
	 * NULL-terminated array of (attribute_name,attribute_value) pairs<br>
	 * C type : const char**
	 */
	public com.sun.jna.ptr.PointerByReference attr;
	/**
	 * pointer to next chunk of the attributes list<br>
	 * C type : CvAttrList*
	 */
	public fr.prima.jna.opencv.cxtypes.CvAttrList.ByReference next;
	public CvAttrList() {
		super();
	}
	/**
	 * @param attr NULL-terminated array of (attribute_name,attribute_value) pairs<br>
	 * C type : const char**<br>
	 * @param next pointer to next chunk of the attributes list<br>
	 * C type : CvAttrList*
	 */
	public CvAttrList(com.sun.jna.ptr.PointerByReference attr, fr.prima.jna.opencv.cxtypes.CvAttrList.ByReference next) {
		super();
		this.attr = attr;
		this.next = next;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvAttrList newInstance() { return new CvAttrList(); }
	public static CvAttrList[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvAttrList.class, arrayLength);
	}
	public static class ByReference extends CvAttrList implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvAttrList implements com.sun.jna.Structure.ByValue {}
}
