package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvBox2D extends com.ochafik.lang.jnaerator.runtime.Structure<CvBox2D, CvBox2D.ByValue, CvBox2D.ByReference> {
	/**
	 * center of the box<br>
	 * C type : CvPoint2D32f
	 */
	public fr.prima.jna.opencv.cxtypes.CvPoint2D32f center;
	/**
	 * box width and length<br>
	 * C type : CvSize2D32f
	 */
	public fr.prima.jna.opencv.cxtypes.CvSize2D32f size;
	/**
	 * angle between the horizontal axis<br>
	 * and the first side (i.e. length) in degrees
	 */
	public float angle;
	public CvBox2D() {
		super();
	}
	/**
	 * @param center center of the box<br>
	 * C type : CvPoint2D32f<br>
	 * @param size box width and length<br>
	 * C type : CvSize2D32f<br>
	 * @param angle angle between the horizontal axis<br>
	 * and the first side (i.e. length) in degrees
	 */
	public CvBox2D(fr.prima.jna.opencv.cxtypes.CvPoint2D32f center, fr.prima.jna.opencv.cxtypes.CvSize2D32f size, float angle) {
		super();
		this.center = center;
		this.size = size;
		this.angle = angle;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvBox2D newInstance() { return new CvBox2D(); }
	public static CvBox2D[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvBox2D.class, arrayLength);
	}
	public static class ByReference extends CvBox2D implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvBox2D implements com.sun.jna.Structure.ByValue {}
}
