package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvContour extends com.ochafik.lang.jnaerator.runtime.Structure<CvContour, CvContour.ByValue, CvContour.ByReference> {
	public int flags;
	public int header_size;
	/// C type : CvSeq*
	public fr.prima.jna.opencv.cxtypes.CvSeq.ByReference h_prev;
	/// C type : CvSeq*
	public fr.prima.jna.opencv.cxtypes.CvSeq.ByReference h_next;
	/// C type : CvSeq*
	public fr.prima.jna.opencv.cxtypes.CvSeq.ByReference v_prev;
	/// C type : CvSeq*
	public fr.prima.jna.opencv.cxtypes.CvSeq.ByReference v_next;
	public int total;
	public int elem_size;
	/// C type : char*
	public com.sun.jna.Pointer block_max;
	/// C type : char*
	public com.sun.jna.Pointer ptr;
	public int delta_elems;
	/// C type : CvMemStorage*
	public fr.prima.jna.opencv.cxtypes.CvMemStorage.ByReference storage;
	/// C type : CvSeqBlock*
	public fr.prima.jna.opencv.cxtypes.CvSeqBlock.ByReference free_blocks;
	/// C type : CvSeqBlock*
	public fr.prima.jna.opencv.cxtypes.CvSeqBlock.ByReference first;
	/// C type : CvRect
	public fr.prima.jna.opencv.cxtypes.CvRect rect;
	public int color;
	/// C type : int[3]
	public int[] reserved = new int[(3)];
	public CvContour() {
		super();
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvContour newInstance() { return new CvContour(); }
	public static CvContour[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvContour.class, arrayLength);
	}
	public static class ByReference extends CvContour implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvContour implements com.sun.jna.Structure.ByValue {}
}
