package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvFileNode extends com.ochafik.lang.jnaerator.runtime.Structure<CvFileNode, CvFileNode.ByValue, CvFileNode.ByReference> {
	public int tag;
	/**
	 * type information<br>
	 * (only for user-defined object, for others it is 0)<br>
	 * C type : CvTypeInfo*
	 */
	public fr.prima.jna.opencv.cxtypes.CvTypeInfo.ByReference info;
	/// C type : data_union
	public data_union data;
	/// <i>native declaration : cxtypes.h:1673</i>
	public static class data_union extends com.ochafik.lang.jnaerator.runtime.Union<data_union, data_union.ByValue, data_union.ByReference> {
		/// scalar floating-point number
		public double f;
		/// scalar integer number
		public int i;
		/**
		 * text string<br>
		 * C type : CvString
		 */
		public fr.prima.jna.opencv.cxtypes.CvString str;
		/**
		 * sequence (ordered collection of file nodes)<br>
		 * C type : CvSeq*
		 */
		public fr.prima.jna.opencv.cxtypes.CvSeq.ByReference seq;
		/**
		 * map (collection of named file nodes)<br>
		 * C type : CvFileNodeHash*
		 */
		public fr.prima.jna.opencv.cxtypes.CxtypesLibrary.CvGenericHash map;
		public data_union() {
			super();
		}
		/**
		 * @param seq sequence (ordered collection of file nodes)<br>
		 * C type : CvSeq*
		 */
		public data_union(fr.prima.jna.opencv.cxtypes.CvSeq.ByReference seq) {
			super();
			this.seq = seq;
			setType(fr.prima.jna.opencv.cxtypes.CvSeq.ByReference.class);
		}
		/// @param i scalar integer number
		public data_union(int i) {
			super();
			this.i = i;
			setType(java.lang.Integer.TYPE);
		}
		/// @param f scalar floating-point number
		public data_union(double f) {
			super();
			this.f = f;
			setType(java.lang.Double.TYPE);
		}
		/**
		 * @param map map (collection of named file nodes)<br>
		 * C type : CvFileNodeHash*
		 */
		public data_union(fr.prima.jna.opencv.cxtypes.CxtypesLibrary.CvGenericHash map) {
			super();
			this.map = map;
			setType(fr.prima.jna.opencv.cxtypes.CxtypesLibrary.CvGenericHash.class);
		}
		/**
		 * @param str text string<br>
		 * C type : CvString
		 */
		public data_union(fr.prima.jna.opencv.cxtypes.CvString str) {
			super();
			this.str = str;
			setType(fr.prima.jna.opencv.cxtypes.CvString.class);
		}
		protected ByReference newByReference() { return new ByReference(); }
		protected ByValue newByValue() { return new ByValue(); }
		protected data_union newInstance() { return new data_union(); }
		public static data_union[] newArray(int arrayLength) {
			return com.ochafik.lang.jnaerator.runtime.Union.newArray(data_union.class, arrayLength);
		}
		public static class ByReference extends data_union implements com.sun.jna.Structure.ByReference {}
		public static class ByValue extends data_union implements com.sun.jna.Structure.ByValue {}
	}
	public CvFileNode() {
		super();
	}
	/**
	 * @param info type information<br>
	 * (only for user-defined object, for others it is 0)<br>
	 * C type : CvTypeInfo*<br>
	 * @param data C type : data_union
	 */
	public CvFileNode(int tag, fr.prima.jna.opencv.cxtypes.CvTypeInfo.ByReference info, data_union data) {
		super();
		this.tag = tag;
		this.info = info;
		this.data = data;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvFileNode newInstance() { return new CvFileNode(); }
	public static CvFileNode[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvFileNode.class, arrayLength);
	}
	public static class ByReference extends CvFileNode implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvFileNode implements com.sun.jna.Structure.ByValue {}
}
