package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvGraphEdge extends com.ochafik.lang.jnaerator.runtime.Structure<CvGraphEdge, CvGraphEdge.ByValue, CvGraphEdge.ByReference> {
	public int flags;
	public float weight;
	/// C type : CvGraphEdge*[2]
	public fr.prima.jna.opencv.cxtypes.CvGraphEdge.ByReference[] next = new fr.prima.jna.opencv.cxtypes.CvGraphEdge.ByReference[(2)];
	/// C type : CvGraphVtx*[2]
	public fr.prima.jna.opencv.cxtypes.CvGraphVtx.ByReference[] vtx = new fr.prima.jna.opencv.cxtypes.CvGraphVtx.ByReference[(2)];
	public CvGraphEdge() {
		super();
	}
	/**
	 * @param next C type : CvGraphEdge*[2]<br>
	 * @param vtx C type : CvGraphVtx*[2]
	 */
	public CvGraphEdge(int flags, float weight, fr.prima.jna.opencv.cxtypes.CvGraphEdge.ByReference next[], fr.prima.jna.opencv.cxtypes.CvGraphVtx.ByReference vtx[]) {
		super();
		this.flags = flags;
		this.weight = weight;
		if (next.length != this.next.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.next = next;
		if (vtx.length != this.vtx.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.vtx = vtx;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvGraphEdge newInstance() { return new CvGraphEdge(); }
	public static CvGraphEdge[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvGraphEdge.class, arrayLength);
	}
	public static class ByReference extends CvGraphEdge implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvGraphEdge implements com.sun.jna.Structure.ByValue {}
}
