package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvGraphVtx extends com.ochafik.lang.jnaerator.runtime.Structure<CvGraphVtx, CvGraphVtx.ByValue, CvGraphVtx.ByReference> {
	public int flags;
	/// C type : CvGraphEdge*
	public fr.prima.jna.opencv.cxtypes.CvGraphEdge.ByReference first;
	public CvGraphVtx() {
		super();
	}
	/// @param first C type : CvGraphEdge*
	public CvGraphVtx(int flags, fr.prima.jna.opencv.cxtypes.CvGraphEdge.ByReference first) {
		super();
		this.flags = flags;
		this.first = first;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvGraphVtx newInstance() { return new CvGraphVtx(); }
	public static CvGraphVtx[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvGraphVtx.class, arrayLength);
	}
	public static class ByReference extends CvGraphVtx implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvGraphVtx implements com.sun.jna.Structure.ByValue {}
}
