package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvHistogram extends com.ochafik.lang.jnaerator.runtime.Structure<CvHistogram, CvHistogram.ByValue, CvHistogram.ByReference> {
	public int type;
	/// C type : CvArr*
	public fr.prima.jna.opencv.highgui.HighguiLibrary.CvArr bins;
	/**
	 * for uniform histograms<br>
	 * C type : float[32][2]
	 */
	public float[] thresh = new float[32 * 2];
	/**
	 * for non-uniform histograms<br>
	 * C type : float**
	 */
	public com.sun.jna.ptr.PointerByReference thresh2;
	/**
	 * embedded matrix header for array histograms<br>
	 * C type : CvMatND
	 */
	public fr.prima.jna.opencv.cxtypes.CvMatND mat;
	public CvHistogram() {
		super();
	}
	/**
	 * @param bins C type : CvArr*<br>
	 * @param thresh for uniform histograms<br>
	 * C type : float[32][2]<br>
	 * @param thresh2 for non-uniform histograms<br>
	 * C type : float**<br>
	 * @param mat embedded matrix header for array histograms<br>
	 * C type : CvMatND
	 */
	public CvHistogram(int type, fr.prima.jna.opencv.highgui.HighguiLibrary.CvArr bins, float thresh[], com.sun.jna.ptr.PointerByReference thresh2, fr.prima.jna.opencv.cxtypes.CvMatND mat) {
		super();
		this.type = type;
		this.bins = bins;
		if (thresh.length != this.thresh.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.thresh = thresh;
		this.thresh2 = thresh2;
		this.mat = mat;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvHistogram newInstance() { return new CvHistogram(); }
	public static CvHistogram[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvHistogram.class, arrayLength);
	}
	public static class ByReference extends CvHistogram implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvHistogram implements com.sun.jna.Structure.ByValue {}
}
