package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvMatND extends com.ochafik.lang.jnaerator.runtime.Structure<CvMatND, CvMatND.ByValue, CvMatND.ByReference> {
	public int type;
	public int dims;
	/// C type : int*
	public com.sun.jna.ptr.IntByReference refcount;
	public int hdr_refcount;
	/// C type : data_union
	public data_union data;
	/// C type : dim_struct[32]
	public fr.prima.jna.opencv.cxtypes.CvMatND.dim_struct[] dim = new fr.prima.jna.opencv.cxtypes.CvMatND.dim_struct[(32)];
	/// <i>native declaration : cxtypes.h:671</i>
	public static class data_union extends com.ochafik.lang.jnaerator.runtime.Union<data_union, data_union.ByValue, data_union.ByReference> {
		/// C type : uchar*
		public com.sun.jna.Pointer ptr;
		/// C type : float*
		public com.sun.jna.ptr.FloatByReference fl;
		/// C type : double*
		public com.sun.jna.ptr.DoubleByReference db;
		/// C type : int*
		public com.sun.jna.ptr.IntByReference i;
		/// C type : short*
		public com.sun.jna.ptr.ShortByReference s;
		public data_union() {
			super();
		}
		/// @param db C type : double*
		public data_union(com.sun.jna.ptr.DoubleByReference db) {
			super();
			this.db = db;
			setType(com.sun.jna.ptr.DoubleByReference.class);
		}
		/// @param s C type : short*
		public data_union(com.sun.jna.ptr.ShortByReference s) {
			super();
			this.s = s;
			setType(com.sun.jna.ptr.ShortByReference.class);
		}
		/// @param i C type : int*
		public data_union(com.sun.jna.ptr.IntByReference i) {
			super();
			this.i = i;
			setType(com.sun.jna.ptr.IntByReference.class);
		}
		/// @param fl C type : float*
		public data_union(com.sun.jna.ptr.FloatByReference fl) {
			super();
			this.fl = fl;
			setType(com.sun.jna.ptr.FloatByReference.class);
		}
		/// @param ptr C type : uchar*
		public data_union(com.sun.jna.Pointer ptr) {
			super();
			this.ptr = ptr;
			setType(com.sun.jna.Pointer.class);
		}
		protected ByReference newByReference() { return new ByReference(); }
		protected ByValue newByValue() { return new ByValue(); }
		protected data_union newInstance() { return new data_union(); }
		public static data_union[] newArray(int arrayLength) {
			return com.ochafik.lang.jnaerator.runtime.Union.newArray(data_union.class, arrayLength);
		}
		public static class ByReference extends data_union implements com.sun.jna.Structure.ByReference {}
		public static class ByValue extends data_union implements com.sun.jna.Structure.ByValue {}
	}
	/// <i>native declaration : cxtypes.h:680</i>
	public static class dim_struct extends com.ochafik.lang.jnaerator.runtime.Structure<dim_struct, dim_struct.ByValue, dim_struct.ByReference> {
		public int size;
		public int step;
		public dim_struct() {
			super();
		}
		public dim_struct(int size, int step) {
			super();
			this.size = size;
			this.step = step;
		}
		protected ByReference newByReference() { return new ByReference(); }
		protected ByValue newByValue() { return new ByValue(); }
		protected dim_struct newInstance() { return new dim_struct(); }
		public static dim_struct[] newArray(int arrayLength) {
			return com.ochafik.lang.jnaerator.runtime.Structure.newArray(dim_struct.class, arrayLength);
		}
		public static class ByReference extends dim_struct implements com.sun.jna.Structure.ByReference {}
		public static class ByValue extends dim_struct implements com.sun.jna.Structure.ByValue {}
	}
	public CvMatND() {
		super();
	}
	/**
	 * @param refcount C type : int*<br>
	 * @param data C type : data_union<br>
	 * @param dim C type : dim_struct[32]
	 */
	public CvMatND(int type, int dims, com.sun.jna.ptr.IntByReference refcount, int hdr_refcount, data_union data, fr.prima.jna.opencv.cxtypes.CvMatND.dim_struct dim[]) {
		super();
		this.type = type;
		this.dims = dims;
		this.refcount = refcount;
		this.hdr_refcount = hdr_refcount;
		this.data = data;
		if (dim.length != this.dim.length) 
			throw new java.lang.IllegalArgumentException("Wrong array size !");
		this.dim = dim;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvMatND newInstance() { return new CvMatND(); }
	public static CvMatND[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvMatND.class, arrayLength);
	}
	public static class ByReference extends CvMatND implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvMatND implements com.sun.jna.Structure.ByValue {}
}
