package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvMemStoragePos extends com.ochafik.lang.jnaerator.runtime.Structure<CvMemStoragePos, CvMemStoragePos.ByValue, CvMemStoragePos.ByReference> {
	/// C type : CvMemBlock*
	public fr.prima.jna.opencv.cxtypes.CvMemBlock.ByReference top;
	public int free_space;
	public CvMemStoragePos() {
		super();
	}
	/// @param top C type : CvMemBlock*
	public CvMemStoragePos(fr.prima.jna.opencv.cxtypes.CvMemBlock.ByReference top, int free_space) {
		super();
		this.top = top;
		this.free_space = free_space;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvMemStoragePos newInstance() { return new CvMemStoragePos(); }
	public static CvMemStoragePos[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvMemStoragePos.class, arrayLength);
	}
	public static class ByReference extends CvMemStoragePos implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvMemStoragePos implements com.sun.jna.Structure.ByValue {}
}
