package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvMemBlock extends com.ochafik.lang.jnaerator.runtime.Structure<CvMemBlock, CvMemBlock.ByValue, CvMemBlock.ByReference> {
	/// C type : CvMemBlock*
	public fr.prima.jna.opencv.cxtypes.CvMemBlock.ByReference prev;
	/// C type : CvMemBlock*
	public fr.prima.jna.opencv.cxtypes.CvMemBlock.ByReference next;
	public CvMemBlock() {
		super();
	}
	/**
	 * @param prev C type : CvMemBlock*<br>
	 * @param next C type : CvMemBlock*
	 */
	public CvMemBlock(fr.prima.jna.opencv.cxtypes.CvMemBlock.ByReference prev, fr.prima.jna.opencv.cxtypes.CvMemBlock.ByReference next) {
		super();
		this.prev = prev;
		this.next = next;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvMemBlock newInstance() { return new CvMemBlock(); }
	public static CvMemBlock[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvMemBlock.class, arrayLength);
	}
	public static class ByReference extends CvMemBlock implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvMemBlock implements com.sun.jna.Structure.ByValue {}
}
