package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvModuleInfo extends com.ochafik.lang.jnaerator.runtime.Structure<CvModuleInfo, CvModuleInfo.ByValue, CvModuleInfo.ByReference> {
	/// C type : CvModuleInfo*
	public fr.prima.jna.opencv.cxtypes.CvModuleInfo.ByReference next;
	/// C type : const char*
	public com.sun.jna.Pointer name;
	/// C type : const char*
	public com.sun.jna.Pointer version;
	/// C type : CvPluginFuncInfo*
	public fr.prima.jna.opencv.cxtypes.CvPluginFuncInfo.ByReference func_tab;
	public CvModuleInfo() {
		super();
	}
	/**
	 * @param next C type : CvModuleInfo*<br>
	 * @param name C type : const char*<br>
	 * @param version C type : const char*<br>
	 * @param func_tab C type : CvPluginFuncInfo*
	 */
	public CvModuleInfo(fr.prima.jna.opencv.cxtypes.CvModuleInfo.ByReference next, com.sun.jna.Pointer name, com.sun.jna.Pointer version, fr.prima.jna.opencv.cxtypes.CvPluginFuncInfo.ByReference func_tab) {
		super();
		this.next = next;
		this.name = name;
		this.version = version;
		this.func_tab = func_tab;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvModuleInfo newInstance() { return new CvModuleInfo(); }
	public static CvModuleInfo[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvModuleInfo.class, arrayLength);
	}
	public static class ByReference extends CvModuleInfo implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvModuleInfo implements com.sun.jna.Structure.ByValue {}
}
