package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvPoint3D64f extends com.ochafik.lang.jnaerator.runtime.Structure<CvPoint3D64f, CvPoint3D64f.ByValue, CvPoint3D64f.ByReference> {
	public double x;
	public double y;
	public double z;
	public CvPoint3D64f() {
		super();
	}
	public CvPoint3D64f(double x, double y, double z) {
		super();
		this.x = x;
		this.y = y;
		this.z = z;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvPoint3D64f newInstance() { return new CvPoint3D64f(); }
	public static CvPoint3D64f[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvPoint3D64f.class, arrayLength);
	}
	public static class ByReference extends CvPoint3D64f implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvPoint3D64f implements com.sun.jna.Structure.ByValue {}
}
