package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvPoint extends com.ochafik.lang.jnaerator.runtime.Structure<CvPoint, CvPoint.ByValue, CvPoint.ByReference> {
	public int x;
	public int y;
	public CvPoint() {
		super();
	}
	public CvPoint(int x, int y) {
		super();
		this.x = x;
		this.y = y;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvPoint newInstance() { return new CvPoint(); }
	public static CvPoint[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvPoint.class, arrayLength);
	}
	public static class ByReference extends CvPoint implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvPoint implements com.sun.jna.Structure.ByValue {}
}
