package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvSetElem extends com.ochafik.lang.jnaerator.runtime.Structure<CvSetElem, CvSetElem.ByValue, CvSetElem.ByReference> {
	public int flags;
	/// C type : CvSetElem*
	public fr.prima.jna.opencv.cxtypes.CvSetElem.ByReference next_free;
	public CvSetElem() {
		super();
	}
	/// @param next_free C type : CvSetElem*
	public CvSetElem(int flags, fr.prima.jna.opencv.cxtypes.CvSetElem.ByReference next_free) {
		super();
		this.flags = flags;
		this.next_free = next_free;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvSetElem newInstance() { return new CvSetElem(); }
	public static CvSetElem[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvSetElem.class, arrayLength);
	}
	public static class ByReference extends CvSetElem implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvSetElem implements com.sun.jna.Structure.ByValue {}
}
