package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvSeqReader extends com.ochafik.lang.jnaerator.runtime.Structure<CvSeqReader, CvSeqReader.ByValue, CvSeqReader.ByReference> {
	public int header_size;
	/// C type : CvSeq*
	public fr.prima.jna.opencv.cxtypes.CvSeq.ByReference seq;
	/// C type : CvSeqBlock*
	public fr.prima.jna.opencv.cxtypes.CvSeqBlock.ByReference block;
	/// C type : char*
	public com.sun.jna.Pointer ptr;
	/// C type : char*
	public com.sun.jna.Pointer block_min;
	/// C type : char*
	public com.sun.jna.Pointer block_max;
	public int delta_index;
	/// C type : char*
	public com.sun.jna.Pointer prev_elem;
	public CvSeqReader() {
		super();
	}
	/**
	 * @param seq C type : CvSeq*<br>
	 * @param block C type : CvSeqBlock*<br>
	 * @param ptr C type : char*<br>
	 * @param block_min C type : char*<br>
	 * @param block_max C type : char*<br>
	 * @param prev_elem C type : char*
	 */
	public CvSeqReader(int header_size, fr.prima.jna.opencv.cxtypes.CvSeq.ByReference seq, fr.prima.jna.opencv.cxtypes.CvSeqBlock.ByReference block, com.sun.jna.Pointer ptr, com.sun.jna.Pointer block_min, com.sun.jna.Pointer block_max, int delta_index, com.sun.jna.Pointer prev_elem) {
		super();
		this.header_size = header_size;
		this.seq = seq;
		this.block = block;
		this.ptr = ptr;
		this.block_min = block_min;
		this.block_max = block_max;
		this.delta_index = delta_index;
		this.prev_elem = prev_elem;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvSeqReader newInstance() { return new CvSeqReader(); }
	public static CvSeqReader[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvSeqReader.class, arrayLength);
	}
	public static class ByReference extends CvSeqReader implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvSeqReader implements com.sun.jna.Structure.ByValue {}
}
