package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvSize extends com.ochafik.lang.jnaerator.runtime.Structure<CvSize, CvSize.ByValue, CvSize.ByReference> {
	public int width;
	public int height;
	public CvSize() {
		super();
	}
	public CvSize(int width, int height) {
		super();
		this.width = width;
		this.height = height;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvSize newInstance() { return new CvSize(); }
	public static CvSize[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvSize.class, arrayLength);
	}
	public static class ByReference extends CvSize implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvSize implements com.sun.jna.Structure.ByValue {}
}
