package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvSlice extends com.ochafik.lang.jnaerator.runtime.Structure<CvSlice, CvSlice.ByValue, CvSlice.ByReference> {
	public int start_index;
	public int end_index;
	public CvSlice() {
		super();
	}
	public CvSlice(int start_index, int end_index) {
		super();
		this.start_index = start_index;
		this.end_index = end_index;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvSlice newInstance() { return new CvSlice(); }
	public static CvSlice[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvSlice.class, arrayLength);
	}
	public static class ByReference extends CvSlice implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvSlice implements com.sun.jna.Structure.ByValue {}
}
