package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvSparseNode extends com.ochafik.lang.jnaerator.runtime.Structure<CvSparseNode, CvSparseNode.ByValue, CvSparseNode.ByReference> {
	public int hashval;
	/// C type : CvSparseNode*
	public fr.prima.jna.opencv.cxtypes.CvSparseNode.ByReference next;
	public CvSparseNode() {
		super();
	}
	/// @param next C type : CvSparseNode*
	public CvSparseNode(int hashval, fr.prima.jna.opencv.cxtypes.CvSparseNode.ByReference next) {
		super();
		this.hashval = hashval;
		this.next = next;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvSparseNode newInstance() { return new CvSparseNode(); }
	public static CvSparseNode[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvSparseNode.class, arrayLength);
	}
	public static class ByReference extends CvSparseNode implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvSparseNode implements com.sun.jna.Structure.ByValue {}
}
