package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvSparseMatIterator extends com.ochafik.lang.jnaerator.runtime.Structure<CvSparseMatIterator, CvSparseMatIterator.ByValue, CvSparseMatIterator.ByReference> {
	/// C type : CvSparseMat*
	public fr.prima.jna.opencv.cxtypes.CvSparseMat.ByReference mat;
	/// C type : CvSparseNode*
	public fr.prima.jna.opencv.cxtypes.CvSparseNode.ByReference node;
	public int curidx;
	public CvSparseMatIterator() {
		super();
	}
	/**
	 * @param mat C type : CvSparseMat*<br>
	 * @param node C type : CvSparseNode*
	 */
	public CvSparseMatIterator(fr.prima.jna.opencv.cxtypes.CvSparseMat.ByReference mat, fr.prima.jna.opencv.cxtypes.CvSparseNode.ByReference node, int curidx) {
		super();
		this.mat = mat;
		this.node = node;
		this.curidx = curidx;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvSparseMatIterator newInstance() { return new CvSparseMatIterator(); }
	public static CvSparseMatIterator[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvSparseMatIterator.class, arrayLength);
	}
	public static class ByReference extends CvSparseMatIterator implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvSparseMatIterator implements com.sun.jna.Structure.ByValue {}
}
