package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvString extends com.ochafik.lang.jnaerator.runtime.Structure<CvString, CvString.ByValue, CvString.ByReference> {
	public int len;
	/// C type : char*
	public com.sun.jna.Pointer ptr;
	public CvString() {
		super();
	}
	/// @param ptr C type : char*
	public CvString(int len, com.sun.jna.Pointer ptr) {
		super();
		this.len = len;
		this.ptr = ptr;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvString newInstance() { return new CvString(); }
	public static CvString[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvString.class, arrayLength);
	}
	public static class ByReference extends CvString implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvString implements com.sun.jna.Structure.ByValue {}
}
