package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvTermCriteria extends com.ochafik.lang.jnaerator.runtime.Structure<CvTermCriteria, CvTermCriteria.ByValue, CvTermCriteria.ByReference> {
	/**
	 * may be combination of<br>
	 * CV_TERMCRIT_ITER<br>
	 * CV_TERMCRIT_EPS
	 */
	public int type;
	public int max_iter;
	public double epsilon;
	public CvTermCriteria() {
		super();
	}
	/**
	 * @param type may be combination of<br>
	 * CV_TERMCRIT_ITER<br>
	 * CV_TERMCRIT_EPS
	 */
	public CvTermCriteria(int type, int max_iter, double epsilon) {
		super();
		this.type = type;
		this.max_iter = max_iter;
		this.epsilon = epsilon;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvTermCriteria newInstance() { return new CvTermCriteria(); }
	public static CvTermCriteria[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvTermCriteria.class, arrayLength);
	}
	public static class ByReference extends CvTermCriteria implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvTermCriteria implements com.sun.jna.Structure.ByValue {}
}
