package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IplConvKernel extends com.ochafik.lang.jnaerator.runtime.Structure<IplConvKernel, IplConvKernel.ByValue, IplConvKernel.ByReference> {
	public int nCols;
	public int nRows;
	public int anchorX;
	public int anchorY;
	/// C type : int*
	public com.sun.jna.ptr.IntByReference values;
	public int nShiftR;
	public IplConvKernel() {
		super();
	}
	/// @param values C type : int*
	public IplConvKernel(int nCols, int nRows, int anchorX, int anchorY, com.sun.jna.ptr.IntByReference values, int nShiftR) {
		super();
		this.nCols = nCols;
		this.nRows = nRows;
		this.anchorX = anchorX;
		this.anchorY = anchorY;
		this.values = values;
		this.nShiftR = nShiftR;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected IplConvKernel newInstance() { return new IplConvKernel(); }
	public static IplConvKernel[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(IplConvKernel.class, arrayLength);
	}
	public static class ByReference extends IplConvKernel implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends IplConvKernel implements com.sun.jna.Structure.ByValue {}
}
