package fr.prima.jna.opencv.cxtypes;
/**
 * <i>native declaration : cxtypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class IplROI extends com.ochafik.lang.jnaerator.runtime.Structure<IplROI, IplROI.ByValue, IplROI.ByReference> {
	/// 0 - no COI (all channels are selected), 1 - 0th channel is selected ...
	public int coi;
	public int xOffset;
	public int yOffset;
	public int width;
	public int height;
	public IplROI() {
		super();
	}
	/// @param coi 0 - no COI (all channels are selected), 1 - 0th channel is selected ...
	public IplROI(int coi, int xOffset, int yOffset, int width, int height) {
		super();
		this.coi = coi;
		this.xOffset = xOffset;
		this.yOffset = yOffset;
		this.width = width;
		this.height = height;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected IplROI newInstance() { return new IplROI(); }
	public static IplROI[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(IplROI.class, arrayLength);
	}
	public static class ByReference extends IplROI implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends IplROI implements com.sun.jna.Structure.ByValue {}
}
