package fr.prima.jna.opencv.cvaux;
/**
 * JNA Wrapper for library <b>cvaux</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface CvauxLibrary extends com.sun.jna.Library {
	public static final java.lang.String JNA_LIBRARY_NAME = com.ochafik.lang.jnaerator.runtime.LibraryExtractor.getLibraryPath("cvaux", true, fr.prima.jna.opencv.cvaux.CvauxLibrary.class);
	public static final com.sun.jna.NativeLibrary JNA_NATIVE_LIB = com.sun.jna.NativeLibrary.getInstance(fr.prima.jna.opencv.cvaux.CvauxLibrary.JNA_LIBRARY_NAME, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	public static final fr.prima.jna.opencv.cvaux.CvauxLibrary INSTANCE = (fr.prima.jna.opencv.cvaux.CvauxLibrary)com.sun.jna.Native.loadLibrary(fr.prima.jna.opencv.cvaux.CvauxLibrary.JNA_LIBRARY_NAME, fr.prima.jna.opencv.cvaux.CvauxLibrary.class, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_EIGOBJ_NO_CALLBACK = 0;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_EIGOBJ_INPUT_CALLBACK = 1;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_EIGOBJ_OUTPUT_CALLBACK = 2;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_EIGOBJ_BOTH_CALLBACK = 3;
	/// <i>native declaration : cvaux.h</i>
	public static final int CLIQUE_TIME_OFF = 2;
	/// <i>native declaration : cvaux.h</i>
	public static final int CLIQUE_FOUND = 1;
	/// <i>native declaration : cvaux.h</i>
	public static final int CLIQUE_END = 0;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_UNDEF_SC_PARAM = 12345;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_IDP_BIRCHFIELD_PARAM1 = 25;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_IDP_BIRCHFIELD_PARAM2 = 5;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_IDP_BIRCHFIELD_PARAM3 = 12;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_IDP_BIRCHFIELD_PARAM4 = 15;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_IDP_BIRCHFIELD_PARAM5 = 25;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_DISPARITY_BIRCHFIELD = 0;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_CAMERA_TO_WARP = 1;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_WARP_TO_CAMERA = 2;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCM_OPTIMIZATION_NONE = -2;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCM_OPTIMIZATION_LUT = -1;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCM_OPTIMIZATION_HISTOGRAM = 0;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCMDESC_OPTIMIZATION_ALLOWDOUBLENEST = 10;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCMDESC_OPTIMIZATION_ALLOWTRIPLENEST = 11;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCMDESC_OPTIMIZATION_HISTOGRAM = 4;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCMDESC_ENTROPY = 0;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCMDESC_ENERGY = 1;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCMDESC_HOMOGENITY = 2;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCMDESC_CONTRAST = 3;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCMDESC_CLUSTERTENDENCY = 4;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCMDESC_CLUSTERSHADE = 5;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCMDESC_CORRELATION = 6;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCMDESC_CORRELATIONINFO1 = 7;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCMDESC_CORRELATIONINFO2 = 8;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCMDESC_MAXIMUMPROBABILITY = 9;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCM_ALL = 0;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCM_GLCM = 1;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_GLCM_DESC = 2;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_NUM_FACE_ELEMENTS = 3;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_BG_MODEL_FGD = 0;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_BG_MODEL_MOG = 1;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_BG_MODEL_FGD_SIMPLE = 2;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_BGFG_FGD_LC = 128;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_BGFG_FGD_N1C = 15;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_BGFG_FGD_N2C = 25;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_BGFG_FGD_LCC = 64;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_BGFG_FGD_N1CC = 25;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_BGFG_FGD_N2CC = 40;
	/// <i>native declaration : cvaux.h</i>
	public static final float CV_BGFG_FGD_ALPHA_1 = 0.1F;
	/// <i>native declaration : cvaux.h</i>
	public static final float CV_BGFG_FGD_ALPHA_2 = 0.0050F;
	/// <i>native declaration : cvaux.h</i>
	public static final float CV_BGFG_FGD_ALPHA_3 = 0.1F;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_BGFG_FGD_DELTA = 2;
	/// <i>native declaration : cvaux.h</i>
	public static final float CV_BGFG_FGD_T = 0.9F;
	/// <i>native declaration : cvaux.h</i>
	public static final float CV_BGFG_FGD_MINAREA = 15.0F;
	/// <i>native declaration : cvaux.h</i>
	public static final float CV_BGFG_FGD_BG_UPDATE_TRESH = 0.5F;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_BGFG_MOG_MAX_NGAUSSIANS = 500;
	/// <i>native declaration : cvaux.h</i>
	public static final double CV_BGFG_MOG_BACKGROUND_THRESHOLD = 0.7;
	/// <i>native declaration : cvaux.h</i>
	public static final double CV_BGFG_MOG_STD_THRESHOLD = 2.5;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_BGFG_MOG_WINDOW_SIZE = 200;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_BGFG_MOG_NGAUSSIANS = 5;
	/// <i>native declaration : cvaux.h</i>
	public static final double CV_BGFG_MOG_WEIGHT_INIT = 0.05;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_BGFG_MOG_SIGMA_INIT = 30;
	/// <i>native declaration : cvaux.h</i>
	public static final float CV_BGFG_MOG_MINAREA = 15.0F;
	/// <i>native declaration : cvaux.h</i>
	public static final int CV_BGFG_MOG_NCOLORS = 3;
	/**
	 * Original signature : <code>cvSegmentImage(const CvArr*, CvArr*, double, double, CvMemStorage*)</code><br>
	 * <i>native declaration : cvaux.h:50</i>
	 */
	int cvSegmentImage(fr.prima.jna.opencv.highgui.HighguiLibrary.CvArr srcarr, fr.prima.jna.opencv.highgui.HighguiLibrary.CvArr dstarr, double canny_threshold, double ffill_threshold, fr.prima.jna.opencv.cxtypes.CvMemStorage storage);
	/**
	 * Original signature : <code>cvCalcCovarMatrixEx(int, void*, int, int, uchar*, void*, IplImage*, float*)</code><br>
	 * <i>native declaration : cvaux.h:73</i><br>
	 * @deprecated use the safer methods {@link #cvCalcCovarMatrixEx(int, com.sun.jna.Pointer, int, int, java.nio.ByteBuffer, com.sun.jna.Pointer, fr.prima.jna.opencv.cxtypes.IplImage, java.nio.FloatBuffer)} and {@link #cvCalcCovarMatrixEx(int, com.sun.jna.Pointer, int, int, com.sun.jna.Pointer, com.sun.jna.Pointer, fr.prima.jna.opencv.cxtypes.IplImage, com.sun.jna.ptr.FloatByReference)} instead
	 */
	@java.lang.Deprecated
	int cvCalcCovarMatrixEx(int nObjects, com.sun.jna.Pointer input, int ioFlags, int ioBufSize, com.sun.jna.Pointer buffer, com.sun.jna.Pointer userData, fr.prima.jna.opencv.cxtypes.IplImage avg, com.sun.jna.ptr.FloatByReference covarMatrix);
	/**
	 * Original signature : <code>cvCalcCovarMatrixEx(int, void*, int, int, uchar*, void*, IplImage*, float*)</code><br>
	 * <i>native declaration : cvaux.h:73</i>
	 */
	int cvCalcCovarMatrixEx(int nObjects, com.sun.jna.Pointer input, int ioFlags, int ioBufSize, java.nio.ByteBuffer buffer, com.sun.jna.Pointer userData, fr.prima.jna.opencv.cxtypes.IplImage avg, java.nio.FloatBuffer covarMatrix);
	/**
	 * Original signature : <code>cvCalcEigenObjects(int, void*, void*, int, int, void*, CvTermCriteria*, IplImage*, float*)</code><br>
	 * <i>native declaration : cvaux.h:79</i><br>
	 * @deprecated use the safer methods {@link #cvCalcEigenObjects(int, com.sun.jna.Pointer, com.sun.jna.Pointer, int, int, com.sun.jna.Pointer, fr.prima.jna.opencv.cxtypes.CvTermCriteria, fr.prima.jna.opencv.cxtypes.IplImage, java.nio.FloatBuffer)} and {@link #cvCalcEigenObjects(int, com.sun.jna.Pointer, com.sun.jna.Pointer, int, int, com.sun.jna.Pointer, fr.prima.jna.opencv.cxtypes.CvTermCriteria, fr.prima.jna.opencv.cxtypes.IplImage, com.sun.jna.ptr.FloatByReference)} instead
	 */
	@java.lang.Deprecated
	int cvCalcEigenObjects(int nObjects, com.sun.jna.Pointer input, com.sun.jna.Pointer output, int ioFlags, int ioBufSize, com.sun.jna.Pointer userData, fr.prima.jna.opencv.cxtypes.CvTermCriteria calcLimit, fr.prima.jna.opencv.cxtypes.IplImage avg, com.sun.jna.ptr.FloatByReference eigVals);
	/**
	 * Original signature : <code>cvCalcEigenObjects(int, void*, void*, int, int, void*, CvTermCriteria*, IplImage*, float*)</code><br>
	 * <i>native declaration : cvaux.h:79</i>
	 */
	int cvCalcEigenObjects(int nObjects, com.sun.jna.Pointer input, com.sun.jna.Pointer output, int ioFlags, int ioBufSize, com.sun.jna.Pointer userData, fr.prima.jna.opencv.cxtypes.CvTermCriteria calcLimit, fr.prima.jna.opencv.cxtypes.IplImage avg, java.nio.FloatBuffer eigVals);
	/**
	 * Original signature : <code>cvCalcDecompCoeff(IplImage*, IplImage*, IplImage*)</code><br>
	 * <i>native declaration : cvaux.h:85</i>
	 */
	int cvCalcDecompCoeff(fr.prima.jna.opencv.cxtypes.IplImage obj, fr.prima.jna.opencv.cxtypes.IplImage eigObj, fr.prima.jna.opencv.cxtypes.IplImage avg);
	/**
	 * Original signature : <code>cvEigenDecomposite(IplImage*, int, void*, int, void*, IplImage*, float*)</code><br>
	 * <i>native declaration : cvaux.h:88</i><br>
	 * @deprecated use the safer methods {@link #cvEigenDecomposite(fr.prima.jna.opencv.cxtypes.IplImage, int, com.sun.jna.Pointer, int, com.sun.jna.Pointer, fr.prima.jna.opencv.cxtypes.IplImage, java.nio.FloatBuffer)} and {@link #cvEigenDecomposite(fr.prima.jna.opencv.cxtypes.IplImage, int, com.sun.jna.Pointer, int, com.sun.jna.Pointer, fr.prima.jna.opencv.cxtypes.IplImage, com.sun.jna.ptr.FloatByReference)} instead
	 */
	@java.lang.Deprecated
	int cvEigenDecomposite(fr.prima.jna.opencv.cxtypes.IplImage obj, int nEigObjs, com.sun.jna.Pointer eigInput, int ioFlags, com.sun.jna.Pointer userData, fr.prima.jna.opencv.cxtypes.IplImage avg, com.sun.jna.ptr.FloatByReference coeffs);
	/**
	 * Original signature : <code>cvEigenDecomposite(IplImage*, int, void*, int, void*, IplImage*, float*)</code><br>
	 * <i>native declaration : cvaux.h:88</i>
	 */
	int cvEigenDecomposite(fr.prima.jna.opencv.cxtypes.IplImage obj, int nEigObjs, com.sun.jna.Pointer eigInput, int ioFlags, com.sun.jna.Pointer userData, fr.prima.jna.opencv.cxtypes.IplImage avg, java.nio.FloatBuffer coeffs);
	/**
	 * Original signature : <code>cvEigenProjection(void*, int, int, void*, float*, IplImage*, IplImage*)</code><br>
	 * <i>native declaration : cvaux.h:93</i><br>
	 * @deprecated use the safer methods {@link #cvEigenProjection(com.sun.jna.Pointer, int, int, com.sun.jna.Pointer, java.nio.FloatBuffer, fr.prima.jna.opencv.cxtypes.IplImage, fr.prima.jna.opencv.cxtypes.IplImage)} and {@link #cvEigenProjection(com.sun.jna.Pointer, int, int, com.sun.jna.Pointer, com.sun.jna.ptr.FloatByReference, fr.prima.jna.opencv.cxtypes.IplImage, fr.prima.jna.opencv.cxtypes.IplImage)} instead
	 */
	@java.lang.Deprecated
	int cvEigenProjection(com.sun.jna.Pointer eigInput, int nEigObjs, int ioFlags, com.sun.jna.Pointer userData, com.sun.jna.ptr.FloatByReference coeffs, fr.prima.jna.opencv.cxtypes.IplImage avg, fr.prima.jna.opencv.cxtypes.IplImage proj);
	/**
	 * Original signature : <code>cvEigenProjection(void*, int, int, void*, float*, IplImage*, IplImage*)</code><br>
	 * <i>native declaration : cvaux.h:93</i>
	 */
	int cvEigenProjection(com.sun.jna.Pointer eigInput, int nEigObjs, int ioFlags, com.sun.jna.Pointer userData, java.nio.FloatBuffer coeffs, fr.prima.jna.opencv.cxtypes.IplImage avg, fr.prima.jna.opencv.cxtypes.IplImage proj);
	/**
	 * Original signature : <code>cvCreate2DHMM(int*, int*, int)</code><br>
	 * <i>native declaration : cvaux.h:168</i><br>
	 * @deprecated use the safer methods {@link #cvCreate2DHMM(java.nio.IntBuffer, java.nio.IntBuffer, int)} and {@link #cvCreate2DHMM(com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference, int)} instead
	 */
	@java.lang.Deprecated
	int cvCreate2DHMM(com.sun.jna.ptr.IntByReference stateNumber, com.sun.jna.ptr.IntByReference numMix, int obsSize);
	/**
	 * Original signature : <code>cvCreate2DHMM(int*, int*, int)</code><br>
	 * <i>native declaration : cvaux.h:168</i>
	 */
	int cvCreate2DHMM(java.nio.IntBuffer stateNumber, java.nio.IntBuffer numMix, int obsSize);
	/**
	 * Original signature : <code>cvRelease2DHMM(CvEHMM**)</code><br>
	 * <i>native declaration : cvaux.h:171</i><br>
	 * @deprecated use the safer method {@link #cvRelease2DHMM(fr.prima.jna.opencv.cvaux.CvEHMM.ByReference[])} instead
	 */
	@java.lang.Deprecated
	int cvRelease2DHMM(com.sun.jna.ptr.PointerByReference hmm);
	/**
	 * Original signature : <code>cvRelease2DHMM(CvEHMM**)</code><br>
	 * <i>native declaration : cvaux.h:171</i>
	 */
	int cvRelease2DHMM(fr.prima.jna.opencv.cvaux.CvEHMM.ByReference hmm[]);
	/**
	 * Original signature : <code>cvCreateObsInfo(CvSize, int)</code><br>
	 * <i>native declaration : cvaux.h:180</i>
	 */
	int cvCreateObsInfo(fr.prima.jna.opencv.cxtypes.CvSize.ByValue numObs, int obsSize);
	/**
	 * Original signature : <code>cvReleaseObsInfo(CvImgObsInfo**)</code><br>
	 * <i>native declaration : cvaux.h:183</i><br>
	 * @deprecated use the safer method {@link #cvReleaseObsInfo(fr.prima.jna.opencv.cvaux.CvImgObsInfo.ByReference[])} instead
	 */
	@java.lang.Deprecated
	int cvReleaseObsInfo(com.sun.jna.ptr.PointerByReference obs_info);
	/**
	 * Original signature : <code>cvReleaseObsInfo(CvImgObsInfo**)</code><br>
	 * <i>native declaration : cvaux.h:183</i>
	 */
	int cvReleaseObsInfo(fr.prima.jna.opencv.cvaux.CvImgObsInfo.ByReference obs_info[]);
	/**
	 * Original signature : <code>cvImgToObs_DCT(const CvArr*, float*, CvSize, CvSize, CvSize)</code><br>
	 * <i>native declaration : cvaux.h:189</i><br>
	 * @deprecated use the safer methods {@link #cvImgToObs_DCT(fr.prima.jna.opencv.highgui.HighguiLibrary.CvArr, java.nio.FloatBuffer, fr.prima.jna.opencv.cxtypes.CvSize.ByValue, fr.prima.jna.opencv.cxtypes.CvSize.ByValue, fr.prima.jna.opencv.cxtypes.CvSize.ByValue)} and {@link #cvImgToObs_DCT(fr.prima.jna.opencv.highgui.HighguiLibrary.CvArr, com.sun.jna.ptr.FloatByReference, fr.prima.jna.opencv.cxtypes.CvSize.ByValue, fr.prima.jna.opencv.cxtypes.CvSize.ByValue, fr.prima.jna.opencv.cxtypes.CvSize.ByValue)} instead
	 */
	@java.lang.Deprecated
	int cvImgToObs_DCT(fr.prima.jna.opencv.highgui.HighguiLibrary.CvArr arr, com.sun.jna.ptr.FloatByReference obs, fr.prima.jna.opencv.cxtypes.CvSize.ByValue dctSize, fr.prima.jna.opencv.cxtypes.CvSize.ByValue obsSize, fr.prima.jna.opencv.cxtypes.CvSize.ByValue delta);
	/**
	 * Original signature : <code>cvImgToObs_DCT(const CvArr*, float*, CvSize, CvSize, CvSize)</code><br>
	 * <i>native declaration : cvaux.h:189</i>
	 */
	int cvImgToObs_DCT(fr.prima.jna.opencv.highgui.HighguiLibrary.CvArr arr, java.nio.FloatBuffer obs, fr.prima.jna.opencv.cxtypes.CvSize.ByValue dctSize, fr.prima.jna.opencv.cxtypes.CvSize.ByValue obsSize, fr.prima.jna.opencv.cxtypes.CvSize.ByValue delta);
	/**
	 * Original signature : <code>cvUniformImgSegm(CvImgObsInfo*, CvEHMM*)</code><br>
	 * <i>native declaration : cvaux.h:194</i>
	 */
	int cvUniformImgSegm(fr.prima.jna.opencv.cvaux.CvImgObsInfo obs_info, fr.prima.jna.opencv.cvaux.CvEHMM ehmm);
	/**
	 * Original signature : <code>cvInitMixSegm(CvImgObsInfo**, int, CvEHMM*)</code><br>
	 * <i>native declaration : cvaux.h:197</i><br>
	 * @deprecated use the safer method {@link #cvInitMixSegm(fr.prima.jna.opencv.cvaux.CvImgObsInfo.ByReference[], int, fr.prima.jna.opencv.cvaux.CvEHMM)} instead
	 */
	@java.lang.Deprecated
	int cvInitMixSegm(com.sun.jna.ptr.PointerByReference obs_info_array, int num_img, fr.prima.jna.opencv.cvaux.CvEHMM hmm);
	/**
	 * Original signature : <code>cvInitMixSegm(CvImgObsInfo**, int, CvEHMM*)</code><br>
	 * <i>native declaration : cvaux.h:197</i>
	 */
	int cvInitMixSegm(fr.prima.jna.opencv.cvaux.CvImgObsInfo.ByReference obs_info_array[], int num_img, fr.prima.jna.opencv.cvaux.CvEHMM hmm);
	/**
	 * Original signature : <code>cvEstimateHMMStateParams(CvImgObsInfo**, int, CvEHMM*)</code><br>
	 * <i>native declaration : cvaux.h:202</i><br>
	 * @deprecated use the safer method {@link #cvEstimateHMMStateParams(fr.prima.jna.opencv.cvaux.CvImgObsInfo.ByReference[], int, fr.prima.jna.opencv.cvaux.CvEHMM)} instead
	 */
	@java.lang.Deprecated
	int cvEstimateHMMStateParams(com.sun.jna.ptr.PointerByReference obs_info_array, int num_img, fr.prima.jna.opencv.cvaux.CvEHMM hmm);
	/**
	 * Original signature : <code>cvEstimateHMMStateParams(CvImgObsInfo**, int, CvEHMM*)</code><br>
	 * <i>native declaration : cvaux.h:202</i>
	 */
	int cvEstimateHMMStateParams(fr.prima.jna.opencv.cvaux.CvImgObsInfo.ByReference obs_info_array[], int num_img, fr.prima.jna.opencv.cvaux.CvEHMM hmm);
	/**
	 * Original signature : <code>cvEstimateTransProb(CvImgObsInfo**, int, CvEHMM*)</code><br>
	 * <i>native declaration : cvaux.h:207</i><br>
	 * @deprecated use the safer method {@link #cvEstimateTransProb(fr.prima.jna.opencv.cvaux.CvImgObsInfo.ByReference[], int, fr.prima.jna.opencv.cvaux.CvEHMM)} instead
	 */
	@java.lang.Deprecated
	int cvEstimateTransProb(com.sun.jna.ptr.PointerByReference obs_info_array, int num_img, fr.prima.jna.opencv.cvaux.CvEHMM hmm);
	/**
	 * Original signature : <code>cvEstimateTransProb(CvImgObsInfo**, int, CvEHMM*)</code><br>
	 * <i>native declaration : cvaux.h:207</i>
	 */
	int cvEstimateTransProb(fr.prima.jna.opencv.cvaux.CvImgObsInfo.ByReference obs_info_array[], int num_img, fr.prima.jna.opencv.cvaux.CvEHMM hmm);
	/**
	 * Original signature : <code>cvEstimateObsProb(CvImgObsInfo*, CvEHMM*)</code><br>
	 * <i>native declaration : cvaux.h:212</i>
	 */
	int cvEstimateObsProb(fr.prima.jna.opencv.cvaux.CvImgObsInfo obs_info, fr.prima.jna.opencv.cvaux.CvEHMM hmm);
	/**
	 * Original signature : <code>cvEViterbi(CvImgObsInfo*, CvEHMM*)</code><br>
	 * <i>native declaration : cvaux.h:216</i>
	 */
	int cvEViterbi(fr.prima.jna.opencv.cvaux.CvImgObsInfo obs_info, fr.prima.jna.opencv.cvaux.CvEHMM hmm);
	/**
	 * Original signature : <code>cvMixSegmL2(CvImgObsInfo**, int, CvEHMM*)</code><br>
	 * <i>native declaration : cvaux.h:223</i><br>
	 * @deprecated use the safer method {@link #cvMixSegmL2(fr.prima.jna.opencv.cvaux.CvImgObsInfo.ByReference[], int, fr.prima.jna.opencv.cvaux.CvEHMM)} instead
	 */
	@java.lang.Deprecated
	int cvMixSegmL2(com.sun.jna.ptr.PointerByReference obs_info_array, int num_img, fr.prima.jna.opencv.cvaux.CvEHMM hmm);
	/**
	 * Original signature : <code>cvMixSegmL2(CvImgObsInfo**, int, CvEHMM*)</code><br>
	 * <i>native declaration : cvaux.h:223</i>
	 */
	int cvMixSegmL2(fr.prima.jna.opencv.cvaux.CvImgObsInfo.ByReference obs_info_array[], int num_img, fr.prima.jna.opencv.cvaux.CvEHMM hmm);
	/**
	 * Original signature : <code>cvCreateHandMask(CvSeq*, IplImage*, CvRect*)</code><br>
	 * <i>native declaration : cvaux.h:231</i>
	 */
	int cvCreateHandMask(fr.prima.jna.opencv.cxtypes.CvSeq hand_points, fr.prima.jna.opencv.cxtypes.IplImage img_mask, fr.prima.jna.opencv.cxtypes.CvRect roi);
	/**
	 * Original signature : <code>cvFindHandRegion(CvPoint3D32f*, int, CvSeq*, float*, CvSize2D32f, int, CvPoint3D32f*, CvMemStorage*, CvSeq**)</code><br>
	 * <i>native declaration : cvaux.h:235</i><br>
	 * @deprecated use the safer methods {@link #cvFindHandRegion(fr.prima.jna.opencv.cxtypes.CvPoint3D32f, int, fr.prima.jna.opencv.cxtypes.CvSeq, java.nio.FloatBuffer, fr.prima.jna.opencv.cxtypes.CvSize2D32f.ByValue, int, fr.prima.jna.opencv.cxtypes.CvPoint3D32f, fr.prima.jna.opencv.cxtypes.CvMemStorage, fr.prima.jna.opencv.cxtypes.CvSeq.ByReference[])} and {@link #cvFindHandRegion(fr.prima.jna.opencv.cxtypes.CvPoint3D32f, int, fr.prima.jna.opencv.cxtypes.CvSeq, com.sun.jna.ptr.FloatByReference, fr.prima.jna.opencv.cxtypes.CvSize2D32f.ByValue, int, fr.prima.jna.opencv.cxtypes.CvPoint3D32f, fr.prima.jna.opencv.cxtypes.CvMemStorage, fr.prima.jna.opencv.cxtypes.CvSeq.ByReference[])} instead
	 */
	@java.lang.Deprecated
	int cvFindHandRegion(fr.prima.jna.opencv.cxtypes.CvPoint3D32f points, int count, fr.prima.jna.opencv.cxtypes.CvSeq indexs, com.sun.jna.ptr.FloatByReference line, fr.prima.jna.opencv.cxtypes.CvSize2D32f.ByValue size, int flag, fr.prima.jna.opencv.cxtypes.CvPoint3D32f center, fr.prima.jna.opencv.cxtypes.CvMemStorage storage, com.sun.jna.ptr.PointerByReference numbers);
	/**
	 * Original signature : <code>cvFindHandRegion(CvPoint3D32f*, int, CvSeq*, float*, CvSize2D32f, int, CvPoint3D32f*, CvMemStorage*, CvSeq**)</code><br>
	 * <i>native declaration : cvaux.h:235</i>
	 */
	int cvFindHandRegion(fr.prima.jna.opencv.cxtypes.CvPoint3D32f points, int count, fr.prima.jna.opencv.cxtypes.CvSeq indexs, java.nio.FloatBuffer line, fr.prima.jna.opencv.cxtypes.CvSize2D32f.ByValue size, int flag, fr.prima.jna.opencv.cxtypes.CvPoint3D32f center, fr.prima.jna.opencv.cxtypes.CvMemStorage storage, fr.prima.jna.opencv.cxtypes.CvSeq.ByReference numbers[]);
	/**
	 * Original signature : <code>cvFindHandRegion(CvPoint3D32f*, int, CvSeq*, float*, CvSize2D32f, int, CvPoint3D32f*, CvMemStorage*, CvSeq**)</code><br>
	 * <i>native declaration : cvaux.h:235</i>
	 */
	int cvFindHandRegion(fr.prima.jna.opencv.cxtypes.CvPoint3D32f points, int count, fr.prima.jna.opencv.cxtypes.CvSeq indexs, com.sun.jna.ptr.FloatByReference line, fr.prima.jna.opencv.cxtypes.CvSize2D32f.ByValue size, int flag, fr.prima.jna.opencv.cxtypes.CvPoint3D32f center, fr.prima.jna.opencv.cxtypes.CvMemStorage storage, fr.prima.jna.opencv.cxtypes.CvSeq.ByReference numbers[]);
	/**
	 * Original signature : <code>cvFindHandRegionA(CvPoint3D32f*, int, CvSeq*, float*, CvSize2D32f, int, CvPoint3D32f*, CvMemStorage*, CvSeq**)</code><br>
	 * <i>native declaration : cvaux.h:242</i><br>
	 * @deprecated use the safer methods {@link #cvFindHandRegionA(fr.prima.jna.opencv.cxtypes.CvPoint3D32f, int, fr.prima.jna.opencv.cxtypes.CvSeq, java.nio.FloatBuffer, fr.prima.jna.opencv.cxtypes.CvSize2D32f.ByValue, int, fr.prima.jna.opencv.cxtypes.CvPoint3D32f, fr.prima.jna.opencv.cxtypes.CvMemStorage, fr.prima.jna.opencv.cxtypes.CvSeq.ByReference[])} and {@link #cvFindHandRegionA(fr.prima.jna.opencv.cxtypes.CvPoint3D32f, int, fr.prima.jna.opencv.cxtypes.CvSeq, com.sun.jna.ptr.FloatByReference, fr.prima.jna.opencv.cxtypes.CvSize2D32f.ByValue, int, fr.prima.jna.opencv.cxtypes.CvPoint3D32f, fr.prima.jna.opencv.cxtypes.CvMemStorage, fr.prima.jna.opencv.cxtypes.CvSeq.ByReference[])} instead
	 */
	@java.lang.Deprecated
	int cvFindHandRegionA(fr.prima.jna.opencv.cxtypes.CvPoint3D32f points, int count, fr.prima.jna.opencv.cxtypes.CvSeq indexs, com.sun.jna.ptr.FloatByReference line, fr.prima.jna.opencv.cxtypes.CvSize2D32f.ByValue size, int jc, fr.prima.jna.opencv.cxtypes.CvPoint3D32f center, fr.prima.jna.opencv.cxtypes.CvMemStorage storage, com.sun.jna.ptr.PointerByReference numbers);
	/**
	 * Original signature : <code>cvFindHandRegionA(CvPoint3D32f*, int, CvSeq*, float*, CvSize2D32f, int, CvPoint3D32f*, CvMemStorage*, CvSeq**)</code><br>
	 * <i>native declaration : cvaux.h:242</i>
	 */
	int cvFindHandRegionA(fr.prima.jna.opencv.cxtypes.CvPoint3D32f points, int count, fr.prima.jna.opencv.cxtypes.CvSeq indexs, java.nio.FloatBuffer line, fr.prima.jna.opencv.cxtypes.CvSize2D32f.ByValue size, int jc, fr.prima.jna.opencv.cxtypes.CvPoint3D32f center, fr.prima.jna.opencv.cxtypes.CvMemStorage storage, fr.prima.jna.opencv.cxtypes.CvSeq.ByReference numbers[]);
	/**
	 * Original signature : <code>cvFindHandRegionA(CvPoint3D32f*, int, CvSeq*, float*, CvSize2D32f, int, CvPoint3D32f*, CvMemStorage*, CvSeq**)</code><br>
	 * <i>native declaration : cvaux.h:242</i>
	 */
	int cvFindHandRegionA(fr.prima.jna.opencv.cxtypes.CvPoint3D32f points, int count, fr.prima.jna.opencv.cxtypes.CvSeq indexs, com.sun.jna.ptr.FloatByReference line, fr.prima.jna.opencv.cxtypes.CvSize2D32f.ByValue size, int jc, fr.prima.jna.opencv.cxtypes.CvPoint3D32f center, fr.prima.jna.opencv.cxtypes.CvMemStorage storage, fr.prima.jna.opencv.cxtypes.CvSeq.ByReference numbers[]);
	/**
	 * Original signature : <code>icvDrawMosaic(CvSubdiv2D*, IplImage*, IplImage*)</code><br>
	 * <i>native declaration : cvaux.h:253</i>
	 */
	int icvDrawMosaic(fr.prima.jna.opencv.cv.CvLibrary.CvSubdiv2D subdiv, fr.prima.jna.opencv.cxtypes.IplImage src, fr.prima.jna.opencv.cxtypes.IplImage dst);
	/**
	 * Original signature : <code>icvSubdiv2DCheck(CvSubdiv2D*)</code><br>
	 * <i>native declaration : cvaux.h:257</i>
	 */
	int icvSubdiv2DCheck(fr.prima.jna.opencv.cv.CvLibrary.CvSubdiv2D subdiv);
	/**
	 * Original signature : <code>double icvSqDist2D32f(CvPoint2D32f, CvPoint2D32f)</code><br>
	 * <i>native declaration : cvaux.h:260</i>
	 */
	double icvSqDist2D32f(fr.prima.jna.opencv.cxtypes.CvPoint2D32f.ByValue pt1, fr.prima.jna.opencv.cxtypes.CvPoint2D32f.ByValue pt2);
}
