package fr.prima.jna.opencv.cvaux;
/**
 * <i>native declaration : cvaux.h:283</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvGraphWeightedVtx extends com.ochafik.lang.jnaerator.runtime.Structure<CvGraphWeightedVtx, CvGraphWeightedVtx.ByValue, CvGraphWeightedVtx.ByReference> {
	public CvGraphWeightedVtx() {
		super();
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvGraphWeightedVtx newInstance() { return new CvGraphWeightedVtx(); }
	public static CvGraphWeightedVtx[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvGraphWeightedVtx.class, arrayLength);
	}
	public static class ByReference extends CvGraphWeightedVtx implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvGraphWeightedVtx implements com.sun.jna.Structure.ByValue {}
}
