package fr.prima.jna.opencv.cvaux;
/**
 * <i>native declaration : cvaux.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvImgObsInfo extends com.ochafik.lang.jnaerator.runtime.Structure<CvImgObsInfo, CvImgObsInfo.ByValue, CvImgObsInfo.ByReference> {
	public int obs_x;
	public int obs_y;
	public int obs_size;
	/**
	 * consequtive observations<br>
	 * C type : float*
	 */
	public com.sun.jna.ptr.FloatByReference obs;
	/**
	 * arr of pairs superstate/state to which observation belong<br>
	 * C type : int*
	 */
	public com.sun.jna.ptr.IntByReference state;
	/**
	 * number of mixture to which observation belong<br>
	 * C type : int*
	 */
	public com.sun.jna.ptr.IntByReference mix;
	public CvImgObsInfo() {
		super();
	}
	/**
	 * @param obs consequtive observations<br>
	 * C type : float*<br>
	 * @param state arr of pairs superstate/state to which observation belong<br>
	 * C type : int*<br>
	 * @param mix number of mixture to which observation belong<br>
	 * C type : int*
	 */
	public CvImgObsInfo(int obs_x, int obs_y, int obs_size, com.sun.jna.ptr.FloatByReference obs, com.sun.jna.ptr.IntByReference state, com.sun.jna.ptr.IntByReference mix) {
		super();
		this.obs_x = obs_x;
		this.obs_y = obs_y;
		this.obs_size = obs_size;
		this.obs = obs;
		this.state = state;
		this.mix = mix;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvImgObsInfo newInstance() { return new CvImgObsInfo(); }
	public static CvImgObsInfo[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvImgObsInfo.class, arrayLength);
	}
	public static class ByReference extends CvImgObsInfo implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvImgObsInfo implements com.sun.jna.Structure.ByValue {}
}
