package fr.prima.jna.opencv.cvaux;
/**
 * <i>native declaration : cvaux.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvInput extends com.ochafik.lang.jnaerator.runtime.Union<CvInput, CvInput.ByValue, CvInput.ByReference> {
	/// Conversion Error : CvCallback
	/// C type : void*
	public com.sun.jna.Pointer data;
	public CvInput() {
		super();
	}
	/// @param data C type : void*
	public CvInput(com.sun.jna.Pointer data) {
		super();
		this.data = data;
		setType(com.sun.jna.Pointer.class);
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvInput newInstance() { return new CvInput(); }
	public static CvInput[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Union.newArray(CvInput.class, arrayLength);
	}
	public static class ByReference extends CvInput implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvInput implements com.sun.jna.Structure.ByValue {}
}
