package fr.prima.jna.vlfeat;
/**
 * <i>native declaration : /local_home/softs/sources/vlfeat/vl/dsift.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VlDsiftDescriptorGeometry extends com.ochafik.lang.jnaerator.runtime.Structure<VlDsiftDescriptorGeometry, VlDsiftDescriptorGeometry.ByValue, VlDsiftDescriptorGeometry.ByReference> {
	/// < number of orientation bins
	public int numBinT;
	/// < number of bins along X
	public int numBinX;
	/// < number of bins along Y
	public int numBinY;
	/// < size of bins along X
	public int binSizeX;
	/// < size of bins along Y
	public int binSizeY;
	public VlDsiftDescriptorGeometry() {
		super();
	}
	/**
	 * @param numBinT < number of orientation bins<br>
	 * @param numBinX < number of bins along X<br>
	 * @param numBinY < number of bins along Y<br>
	 * @param binSizeX < size of bins along X<br>
	 * @param binSizeY < size of bins along Y
	 */
	public VlDsiftDescriptorGeometry(int numBinT, int numBinX, int numBinY, int binSizeX, int binSizeY) {
		super();
		this.numBinT = numBinT;
		this.numBinX = numBinX;
		this.numBinY = numBinY;
		this.binSizeX = binSizeX;
		this.binSizeY = binSizeY;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected VlDsiftDescriptorGeometry newInstance() { return new VlDsiftDescriptorGeometry(); }
	public static VlDsiftDescriptorGeometry[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(VlDsiftDescriptorGeometry.class, arrayLength);
	}
	public static class ByReference extends VlDsiftDescriptorGeometry implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends VlDsiftDescriptorGeometry implements com.sun.jna.Structure.ByValue {}
}
