package fr.prima.jna.vlfeat;
/**
 * <i>native declaration : /local_home/softs/sources/vlfeat/vl/dsift.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VlDsiftKeypoint extends com.ochafik.lang.jnaerator.runtime.Structure<VlDsiftKeypoint, VlDsiftKeypoint.ByValue, VlDsiftKeypoint.ByReference> {
	/// < x coordinate
	public double x;
	/// < y coordinate
	public double y;
	/// < scale
	public double s;
	/// < norm
	public double norm;
	public VlDsiftKeypoint() {
		super();
	}
	/**
	 * @param x < x coordinate<br>
	 * @param y < y coordinate<br>
	 * @param s < scale<br>
	 * @param norm < norm
	 */
	public VlDsiftKeypoint(double x, double y, double s, double norm) {
		super();
		this.x = x;
		this.y = y;
		this.s = s;
		this.norm = norm;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected VlDsiftKeypoint newInstance() { return new VlDsiftKeypoint(); }
	public static VlDsiftKeypoint[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(VlDsiftKeypoint.class, arrayLength);
	}
	public static class ByReference extends VlDsiftKeypoint implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends VlDsiftKeypoint implements com.sun.jna.Structure.ByValue {}
}
