package fr.prima.jna.vlfeat;
/**
 * <i>native declaration : /local_home/softs/sources/vlfeat/vl/hikmeans.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VlHIKMTree extends com.ochafik.lang.jnaerator.runtime.Structure<VlHIKMTree, VlHIKMTree.ByValue, VlHIKMTree.ByReference> {
	/// < IKM: data dimensionality
	public int M;
	/// < IKM: K
	public int K;
	/// < IKM: maximum # of iterations
	public int max_niters;
	/// < IKM: method
	public int method;
	/// < Verbosity level
	public int verb;
	/// < Depth of the tree
	public int depth;
	/**
	 * < Tree root node<br>
	 * C type : VlHIKMNode*
	 */
	public fr.prima.jna.vlfeat.VlHIKMNode.ByReference root;
	public VlHIKMTree() {
		super();
	}
	/**
	 * @param M < IKM: data dimensionality<br>
	 * @param K < IKM: K<br>
	 * @param max_niters < IKM: maximum # of iterations<br>
	 * @param method < IKM: method<br>
	 * @param verb < Verbosity level<br>
	 * @param depth < Depth of the tree<br>
	 * @param root < Tree root node<br>
	 * C type : VlHIKMNode*
	 */
	public VlHIKMTree(int M, int K, int max_niters, int method, int verb, int depth, fr.prima.jna.vlfeat.VlHIKMNode.ByReference root) {
		super();
		this.M = M;
		this.K = K;
		this.max_niters = max_niters;
		this.method = method;
		this.verb = verb;
		this.depth = depth;
		this.root = root;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected VlHIKMTree newInstance() { return new VlHIKMTree(); }
	public static VlHIKMTree[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(VlHIKMTree.class, arrayLength);
	}
	public static class ByReference extends VlHIKMTree implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends VlHIKMTree implements com.sun.jna.Structure.ByValue {}
}
