package fr.prima.jna.vlfeat;
/**
 * <i>native declaration : /local_home/softs/sources/vlfeat/vl/ikmeans.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VlIKMFilt extends com.ochafik.lang.jnaerator.runtime.Structure<VlIKMFilt, VlIKMFilt.ByValue, VlIKMFilt.ByReference> {
	/// < data dimensionality
	public int M;
	/// < number of centers
	public int K;
	/// < Learning method
	public int method;
	/// < Lloyd: maximum number of iterations
	public int max_niters;
	/// < verbosity level
	public int verb;
	/**
	 * < centers<br>
	 * C type : vl_ikm_acc*
	 */
	public com.sun.jna.ptr.IntByReference centers;
	/**
	 * < centers inter-distances<br>
	 * C type : vl_ikm_acc*
	 */
	public com.sun.jna.ptr.IntByReference inter_dist;
	public VlIKMFilt() {
		super();
	}
	/**
	 * @param M < data dimensionality<br>
	 * @param K < number of centers<br>
	 * @param method < Learning method<br>
	 * @param max_niters < Lloyd: maximum number of iterations<br>
	 * @param verb < verbosity level<br>
	 * @param centers < centers<br>
	 * C type : vl_ikm_acc*<br>
	 * @param inter_dist < centers inter-distances<br>
	 * C type : vl_ikm_acc*
	 */
	public VlIKMFilt(int M, int K, int method, int max_niters, int verb, com.sun.jna.ptr.IntByReference centers, com.sun.jna.ptr.IntByReference inter_dist) {
		super();
		this.M = M;
		this.K = K;
		this.method = method;
		this.max_niters = max_niters;
		this.verb = verb;
		this.centers = centers;
		this.inter_dist = inter_dist;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected VlIKMFilt newInstance() { return new VlIKMFilt(); }
	public static VlIKMFilt[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(VlIKMFilt.class, arrayLength);
	}
	public static class ByReference extends VlIKMFilt implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends VlIKMFilt implements com.sun.jna.Structure.ByValue {}
}
