package fr.prima.jna.vlfeat;
/**
 * @internal @brief MSER filter <br>
 * * @see @ref mser<br>
 * <i>native declaration : /local_home/softs/sources/vlfeat/vl/mser.h:201</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VlMserFilt extends com.ochafik.lang.jnaerator.runtime.Structure<VlMserFilt, VlMserFilt.ByValue, VlMserFilt.ByReference> {
	/**
	 * @{<br>
	 * < number of dimensions
	 */
	public int ndims;
	/**
	 * < dimensions<br>
	 * C type : int*
	 */
	public com.sun.jna.ptr.IntByReference dims;
	/// < number of image elements (pixels)
	public int nel;
	/**
	 * < N-dimensional subscript<br>
	 * C type : int*
	 */
	public com.sun.jna.ptr.IntByReference subs;
	/**
	 * < another subscript<br>
	 * C type : int*
	 */
	public com.sun.jna.ptr.IntByReference dsubs;
	/**
	 * < strides to move in image data<br>
	 * C type : int*
	 */
	public com.sun.jna.ptr.IntByReference strides;
	/**
	 * < pixel ordering<br>
	 * C type : vl_uint*
	 */
	public com.sun.jna.ptr.IntByReference perm;
	/**
	 * < sequence of join ops<br>
	 * C type : vl_uint*
	 */
	public com.sun.jna.ptr.IntByReference joins;
	/// < number of join ops
	public int njoins;
	/**
	 * @{<br>
	 * < basic regions<br>
	 * C type : VlMserReg*
	 */
	public fr.prima.jna.vlfeat.VlMserReg r;
	/**
	 * < extremal tree<br>
	 * C type : VlMserExtrReg*
	 */
	public fr.prima.jna.vlfeat.VlMserExtrReg er;
	/**
	 * < maximally stable extremal regions<br>
	 * C type : vl_uint*
	 */
	public com.sun.jna.ptr.IntByReference mer;
	/// < number of extremal regions
	public int ner;
	/// < number of maximally stable extr. reg.
	public int nmer;
	/// < size of er buffer
	public int rer;
	/// < size of mer buffer
	public int rmer;
	/**
	 * @{<br>
	 * < moment accumulator.<br>
	 * C type : float*
	 */
	public com.sun.jna.ptr.FloatByReference acc;
	/**
	 * < ellipsoids list.<br>
	 * C type : float*
	 */
	public com.sun.jna.ptr.FloatByReference ell;
	/// < size of ell buffer
	public int rell;
	/// < number of ellipsoids extracted
	public int nell;
	/// < number of dof of ellipsoids.
	public int dof;
	/**
	 * @{<br>
	 * < be verbose<br>
	 * C type : vl_bool
	 */
	public int verbose;
	/// < delta filter parameter
	public int delta;
	/// < badness test parameter
	public double max_area;
	/// < badness test parameter
	public double min_area;
	/// < badness test parameter
	public double max_variation;
	/// < minimum diversity
	public double min_diversity;
	/**
	 * run statistic<br>
	 * C type : VlMserStats
	 */
	public fr.prima.jna.vlfeat.VlMserStats stats;
	public VlMserFilt() {
		super();
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected VlMserFilt newInstance() { return new VlMserFilt(); }
	public static VlMserFilt[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(VlMserFilt.class, arrayLength);
	}
	public static class ByReference extends VlMserFilt implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends VlMserFilt implements com.sun.jna.Structure.ByValue {}
}
