package fr.prima.jna.vlfeat;
/**
 * <i>native declaration : /local_home/softs/sources/vlfeat/vl/sift.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class VlSiftKeypoint extends com.ochafik.lang.jnaerator.runtime.Structure<VlSiftKeypoint, VlSiftKeypoint.ByValue, VlSiftKeypoint.ByReference> {
	/// < o coordinate (octave).
	public int o;
	/// < Integer unnormalized x coordinate.
	public int ix;
	/// < Integer unnormalized y coordinate.
	public int iy;
	/// < Integer s coordinate.
	public int is;
	/// < x coordinate.
	public float x;
	/// < u coordinate.
	public float y;
	/// < x coordinate.
	public float s;
	/// < scale.
	public float sigma;
	public VlSiftKeypoint() {
		super();
	}
	/**
	 * @param o < o coordinate (octave).<br>
	 * @param ix < Integer unnormalized x coordinate.<br>
	 * @param iy < Integer unnormalized y coordinate.<br>
	 * @param is < Integer s coordinate.<br>
	 * @param x < x coordinate.<br>
	 * @param y < u coordinate.<br>
	 * @param s < x coordinate.<br>
	 * @param sigma < scale.
	 */
	public VlSiftKeypoint(int o, int ix, int iy, int is, float x, float y, float s, float sigma) {
		super();
		this.o = o;
		this.ix = ix;
		this.iy = iy;
		this.is = is;
		this.x = x;
		this.y = y;
		this.s = s;
		this.sigma = sigma;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected VlSiftKeypoint newInstance() { return new VlSiftKeypoint(); }
	public static VlSiftKeypoint[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(VlSiftKeypoint.class, arrayLength);
	}
	public static class ByReference extends VlSiftKeypoint implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends VlSiftKeypoint implements com.sun.jna.Structure.ByValue {}
}
