package fr.prima.jna.opencv.cvver;
/**
 * JNA Wrapper for library <b>cvver</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface CvverLibrary extends com.sun.jna.Library {
	public static final java.lang.String JNA_LIBRARY_NAME = com.ochafik.lang.jnaerator.runtime.LibraryExtractor.getLibraryPath("cvver", true, fr.prima.jna.opencv.cvver.CvverLibrary.class);
	public static final com.sun.jna.NativeLibrary JNA_NATIVE_LIB = com.sun.jna.NativeLibrary.getInstance(fr.prima.jna.opencv.cvver.CvverLibrary.JNA_LIBRARY_NAME, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	public static final fr.prima.jna.opencv.cvver.CvverLibrary INSTANCE = (fr.prima.jna.opencv.cvver.CvverLibrary)com.sun.jna.Native.loadLibrary(fr.prima.jna.opencv.cvver.CvverLibrary.JNA_LIBRARY_NAME, fr.prima.jna.opencv.cvver.CvverLibrary.class, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	/// <i>native declaration : cvver.h</i>
	public static final int CV_MAJOR_VERSION = 1;
	/// <i>native declaration : cvver.h</i>
	public static final int CV_MINOR_VERSION = 0;
	/// <i>native declaration : cvver.h</i>
	public static final int CV_SUBMINOR_VERSION = 0;
	/// <i>native declaration : cvver.h</i>
	public static final java.lang.String CV_VERSION = "1.0.0";
}
