package fr.prima.jna.opencv.cvcompat;
/**
 * JNA Wrapper for library <b>cvcompat</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface CvcompatLibrary extends com.sun.jna.Library {
	public static final java.lang.String JNA_LIBRARY_NAME = com.ochafik.lang.jnaerator.runtime.LibraryExtractor.getLibraryPath("cvcompat", true, fr.prima.jna.opencv.cvcompat.CvcompatLibrary.class);
	public static final com.sun.jna.NativeLibrary JNA_NATIVE_LIB = com.sun.jna.NativeLibrary.getInstance(fr.prima.jna.opencv.cvcompat.CvcompatLibrary.JNA_LIBRARY_NAME, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	public static final fr.prima.jna.opencv.cvcompat.CvcompatLibrary INSTANCE = (fr.prima.jna.opencv.cvcompat.CvcompatLibrary)com.sun.jna.Native.loadLibrary(fr.prima.jna.opencv.cvcompat.CvcompatLibrary.JNA_LIBRARY_NAME, fr.prima.jna.opencv.cvcompat.CvcompatLibrary.class, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	/// <i>native declaration : cvcompat.h</i>
	public static final int IPL_GAUSSIAN_5x5 = 7;
	/// <i>native declaration : cvcompat.h</i>
	public static final int CV_RODRIGUES_M2V = 0;
	/// <i>native declaration : cvcompat.h</i>
	public static final int CV_RODRIGUES_V2M = 1;
	/// <i>native declaration : cvcompat.h</i>
	public static final int CV_SHIFT_NONE = 2;
	/// <i>native declaration : cvcompat.h</i>
	public static final int CV_SHIFT_LEFT = 1;
	/// <i>native declaration : cvcompat.h</i>
	public static final int CV_SHIFT_RIGHT = 3;
	/// <i>native declaration : cvcompat.h</i>
	public static final int CV_SHIFT_UP = 6;
	/// <i>native declaration : cvcompat.h</i>
	public static final int CV_SHIFT_DOWN = 10;
	/// <i>native declaration : cvcompat.h</i>
	public static final int CV_SHIFT_LU = 5;
	/// <i>native declaration : cvcompat.h</i>
	public static final int CV_SHIFT_RU = 7;
	/// <i>native declaration : cvcompat.h</i>
	public static final int CV_SHIFT_LD = 9;
	/// <i>native declaration : cvcompat.h</i>
	public static final int CV_SHIFT_RD = 11;
	/**
	 * Original signature : <code>cvMat(rows*)</code><br>
	 * <i>native declaration : cvcompat.h:112</i>
	 */
	int cvMat(fr.prima.jna.opencv.cvcompat.CvcompatLibrary.rows count);
	/// Pointer to unknown (opaque) type
	public static class rows extends com.sun.jna.PointerType {
		public rows(com.sun.jna.Pointer pointer) {
			super(pointer);
		}
		public rows() {
			super();
		}
	}
}
