package fr.prima.jna.opencv.cxerror;
/**
 * JNA Wrapper for library <b>cxerror</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface CxerrorLibrary extends com.sun.jna.Library {
	public static final java.lang.String JNA_LIBRARY_NAME = com.ochafik.lang.jnaerator.runtime.LibraryExtractor.getLibraryPath("cxerror", true, fr.prima.jna.opencv.cxerror.CxerrorLibrary.class);
	public static final com.sun.jna.NativeLibrary JNA_NATIVE_LIB = com.sun.jna.NativeLibrary.getInstance(fr.prima.jna.opencv.cxerror.CxerrorLibrary.JNA_LIBRARY_NAME, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	public static final fr.prima.jna.opencv.cxerror.CxerrorLibrary INSTANCE = (fr.prima.jna.opencv.cxerror.CxerrorLibrary)com.sun.jna.Native.loadLibrary(fr.prima.jna.opencv.cxerror.CxerrorLibrary.JNA_LIBRARY_NAME, fr.prima.jna.opencv.cxerror.CxerrorLibrary.class, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsOk = 0;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsBackTrace = -1;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsError = -2;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsInternal = -3;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsNoMem = -4;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsBadArg = -5;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsBadFunc = -6;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsNoConv = -7;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsAutoTrace = -8;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_HeaderIsNull = -9;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_BadImageSize = -10;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_BadOffset = -11;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_BadDataPtr = -12;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_BadStep = -13;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_BadModelOrChSeq = -14;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_BadNumChannels = -15;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_BadNumChannel1U = -16;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_BadDepth = -17;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_BadAlphaChannel = -18;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_BadOrder = -19;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_BadOrigin = -20;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_BadAlign = -21;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_BadCallBack = -22;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_BadTileSize = -23;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_BadCOI = -24;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_BadROISize = -25;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_MaskIsTiled = -26;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsNullPtr = -27;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsVecLengthErr = -28;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsFilterStructContentErr = -29;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsKernelStructContentErr = -30;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsFilterOffsetErr = -31;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsBadSize = -201;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsDivByZero = -202;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsInplaceNotSupported = -203;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsObjectNotFound = -204;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsUnmatchedFormats = -205;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsBadFlag = -206;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsBadPoint = -207;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsBadMask = -208;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsUnmatchedSizes = -209;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsUnsupportedFormat = -210;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsOutOfRange = -211;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsParseError = -212;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsNotImplemented = -213;
	/// <i>native declaration : cxerror.h</i>
	public static final int CV_StsBadMemBlock = -214;
	/**
	 * define<br>
	 * Conversion Error : null<br>
	 * SKIPPED:<br>
	 * <i>native declaration : cxerror.h</i><br>
	 * null < 0
	 */
}
