package fr.prima.jna.opencv.cxmisc;
/**
 * JNA Wrapper for library <b>cxmisc</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface CxmiscLibrary extends com.sun.jna.Library {
	public static final java.lang.String JNA_LIBRARY_NAME = com.ochafik.lang.jnaerator.runtime.LibraryExtractor.getLibraryPath("cxmisc", true, fr.prima.jna.opencv.cxmisc.CxmiscLibrary.class);
	public static final com.sun.jna.NativeLibrary JNA_NATIVE_LIB = com.sun.jna.NativeLibrary.getInstance(fr.prima.jna.opencv.cxmisc.CxmiscLibrary.JNA_LIBRARY_NAME, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	public static final fr.prima.jna.opencv.cxmisc.CxmiscLibrary INSTANCE = (fr.prima.jna.opencv.cxmisc.CxmiscLibrary)com.sun.jna.Native.loadLibrary(fr.prima.jna.opencv.cxmisc.CxmiscLibrary.JNA_LIBRARY_NAME, fr.prima.jna.opencv.cxmisc.CxmiscLibrary.class, com.ochafik.lang.jnaerator.runtime.MangledFunctionMapper.DEFAULT_OPTIONS);
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_MAX_INLINE_MAT_OP_SIZE = 10;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_MAX_LOCAL_MAT_SIZE = 32;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_DEFAULT_IMAGE_ROW_ALIGN = 4;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_DEFAULT_MAT_ROW_ALIGN = 1;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_MALLOC_ALIGN = 32;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_STORAGE_BLOCK_SIZE = ((1 << 16) - 128);
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_SPARSE_MAT_BLOCK = (1 << 12);
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_SPARSE_HASH_SIZE0 = (1 << 10);
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_SPARSE_HASH_RATIO = 3;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_MAX_STRLEN = 1024;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_MAX_THREADS = 1;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_STUB_STEP = (1 << 30);
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_ORIGIN_TL = 0;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_ORIGIN_BL = 1;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_POS_INF = 2139095040;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_NEG_INF = -2139095041;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_1F = 1065353216;
	/// <i>native declaration : cxmisc.h</i>
	public static final java.lang.String cvUnsupportedFormat = "Unsupported format";
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_PLUGIN_NONE = 0;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_PLUGIN_OPTCV = 1;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_PLUGIN_IPPCV = 2;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_PLUGIN_IPPI = 3;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_PLUGIN_IPPS = 4;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_PLUGIN_IPPVM = 5;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_PLUGIN_IPPCC = 6;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_PLUGIN_MKL = 8;
	/// <i>native declaration : cxmisc.h</i>
	public static final int CV_PLUGIN_MAX = 16;
	/**
	 * Original signature : <code>void* cvAlignPtr(const void*, int)</code><br>
	 * <i>native declaration : cxmisc.h:236</i>
	 */
	com.sun.jna.Pointer cvAlignPtr(com.sun.jna.Pointer ptr, int align);
	/**
	 * Original signature : <code>int cvAlign(int, int)</code><br>
	 * <i>native declaration : cxmisc.h:242</i>
	 */
	int cvAlign(int size, int align);
}
