package fr.prima.jna.opencv.ml;
/**
 * <i>native declaration : ml.h:66</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a>, <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CvVectors extends com.ochafik.lang.jnaerator.runtime.Structure<CvVectors, CvVectors.ByValue, CvVectors.ByReference> {
	public int type;
	public int dims;
	public int count;
	/// C type : CvVectors*
	public fr.prima.jna.opencv.ml.CvVectors.ByReference next;
	/// C type : data_union
	public data_union data;
	/// <i>native declaration : ml.h:71</i>
	public static class data_union extends com.ochafik.lang.jnaerator.runtime.Union<data_union, data_union.ByValue, data_union.ByReference> {
		/// C type : uchar**
		public com.sun.jna.ptr.PointerByReference ptr;
		/// C type : float**
		public com.sun.jna.ptr.PointerByReference fl;
		/// C type : double**
		public com.sun.jna.ptr.PointerByReference db;
		public data_union() {
			super();
		}
		/// @param ptr_or_fl_or_db C type : uchar**, or C type : float**, or C type : double**
		public data_union(com.sun.jna.ptr.PointerByReference ptr_or_fl_or_db) {
			super();
			this.db = this.fl = this.ptr = ptr_or_fl_or_db;
			setType(com.sun.jna.ptr.PointerByReference.class);
		}
		protected ByReference newByReference() { return new ByReference(); }
		protected ByValue newByValue() { return new ByValue(); }
		protected data_union newInstance() { return new data_union(); }
		public static data_union[] newArray(int arrayLength) {
			return com.ochafik.lang.jnaerator.runtime.Union.newArray(data_union.class, arrayLength);
		}
		public static class ByReference extends data_union implements com.sun.jna.Structure.ByReference {}
		public static class ByValue extends data_union implements com.sun.jna.Structure.ByValue {}
	}
	public CvVectors() {
		super();
	}
	/**
	 * @param next C type : CvVectors*<br>
	 * @param data C type : data_union
	 */
	public CvVectors(int type, int dims, int count, fr.prima.jna.opencv.ml.CvVectors.ByReference next, data_union data) {
		super();
		this.type = type;
		this.dims = dims;
		this.count = count;
		this.next = next;
		this.data = data;
	}
	protected ByReference newByReference() { return new ByReference(); }
	protected ByValue newByValue() { return new ByValue(); }
	protected CvVectors newInstance() { return new CvVectors(); }
	public static CvVectors[] newArray(int arrayLength) {
		return com.ochafik.lang.jnaerator.runtime.Structure.newArray(CvVectors.class, arrayLength);
	}
	public static class ByReference extends CvVectors implements com.sun.jna.Structure.ByReference {}
	public static class ByValue extends CvVectors implements com.sun.jna.Structure.ByValue {}
}
